name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ""
type: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Development environment 

  - type: input
    attributes:
      label: Operation system
      description: Choose the operating system you are using.
      placeholder: "e.g: Windows 10 22H2, Fedora 42, Ubuntu 25.04, macOS Sonoma 14.0...."
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Version
      description: What is the currently developed version? Typically, you can view it in the terminal or command line interface when running your project.
      options:
        - v0.1.2-beta
        - v0.1.1-beta
      default: 0
    validations:
      required: true

  - type: input
    attributes:
      label: SDL version
      description: What SDL version is the currently used project based on
      placeholder: "e.g: SDL 3.3.0"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug report

  - type: input
    attributes:
      label: Question description
      description: What problems did you encounter during project development? Please provide a brief description.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    attributes:
      label: Bug reproduction
      description: Clearly and concisely describe the bug you encountered (avoiding vague expressions).
      placeholder: |
        1. Open .....
        2. ........
        3. expected effect
        4. actual effect
        .....

  - type: markdown
    attributes:
      value: |
        ## Supplementary content

  - type: textarea
    attributes:
      label: Screenshot or Screenrecord
      description: If applicable, please paste the link or attachment
      placeholder: |
        `![screenshot](/path/to/screenshot.jpg)`
        `[Video](/path/to/your/video.mp4)`
