name: Bug 报告
description: 提交 bug 报告
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ""
type: bug
body:
  - type: markdown
    attributes:
      value: |
        ## 开发环境 

  - type: input
    attributes:
      label: 操作系统
      description: 请选择您正在使用的操作系统。
      placeholder: "例如: Windows 10 22H2, Fedora 42, Ubuntu 25.04, macOS Sonoma 14.0...."
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 版本
      description: 当前开发的版本是什么？通常，您可以在运行项目时在终端或命令行界面中查看。
      options:
        - v0.1.2-beta
        - v0.1.1-beta
      default: 0
    validations:
      required: true

  - type: input
    attributes:
      label: SDL版本
      description: 当前使用的项目基于哪个SDL版本
      placeholder: "例如: SDL 3.3.0"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug报告

  - type: input
    attributes:
      label: 问题描述
      description: 您在项目开发过程中遇到了什么问题？请提供简要描述。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 相关日志输出
      description: 请复制粘贴任何相关的日志输出。这将自动格式化为代码，因此不需要使用反引号。
      render: shell

  - type: textarea
    attributes:
      label: Bug复现
      description: 清晰简洁地描述您遇到的bug（避免模糊表达）。
      placeholder: |
        1. 打开 .....
        2. ........
        3. 预期效果
        4. 实际效果
        .....

  - type: markdown
    attributes:
      value: |
        ## 补充内容

  - type: textarea
    attributes:
      label: 截图或录屏
      description: 如果适用，请粘贴链接或附件
      placeholder: |
        `![screenshot](/path/to/screenshot.jpg)`
        `[Video](/path/to/your/video.mp4)`