.TH "basic_API" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_API \- Basic_API
.PP
 \- Basic Module API\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Basic Module API\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
