.TH "D:/Coding/S3GF/src/Core.h" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Core.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Basic\&.h'\fP
.br
\fR#include 'Components\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBS3GF::Renderer\fP"
.br
.ti -1c
.RI "class \fBS3GF::Window\fP"
.br
.ti -1c
.RI "struct \fBS3GF::Window::Geometry\fP"
.br
.ti -1c
.RI "class \fBS3GF::EventSystem\fP"
.br
.ti -1c
.RI "class \fBS3GF::Engine\fP"
.br
.ti -1c
.RI "class \fBS3GF::Font\fP"
.br
.ti -1c
.RI "class \fBS3GF::TextSystem\fP"
.br
.ti -1c
.RI "struct \fBS3GF::TextSystem::Text\fP"
.br
.ti -1c
.RI "struct \fBS3GF::TextSystem::FontEngine\fP"
.br
.ti -1c
.RI "class \fBS3GF::FontDatabase\fP"
.br
.ti -1c
.RI "struct \fBS3GF::FontDatabase::FontInfo\fP"
.br
.ti -1c
.RI "class \fBS3GF::AudioSystem\fP"
.br
.ti -1c
.RI "struct \fBS3GF::AudioSystem::Audio\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS3GF_CORE_H\fP"
.br
.ti -1c
.RI "#define \fBS3GF_FULL_VERSION\fP   'v0\&.1\&.1\-beta'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBS3GF::FontMap\fP = std::unordered_map<std::string, std::string>"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S3GF_CORE_H"

.SS "#define S3GF_FULL_VERSION   'v0\&.1\&.1\-beta'"

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
