.TH "D:/Coding/S3GF/src/Utils/Cursor.h" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Utils/Cursor.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Logger\&.h'\fP
.br
\fR#include '\&.\&./Components\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBS3GF::Cursor\fP"
.br
.RI "鼠标光标 "
.ti -1c
.RI "struct \fBS3GF::Cursor::UserCustom\fP"
.br
.RI "用户自定义鼠标光标数据 "
.ti -1c
.RI "struct \fBS3GF::Cursor::UserCustom::HotPoint\fP"
.br
.RI "用于定义鼠标光标的热点坐标 "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
