.TH "D:/Coding/S3GF/src/Utils/DateTime.h" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Utils/DateTime.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Libs\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBS3GF::DateTime\fP"
.br
.ti -1c
.RI "struct \fBS3GF::DateTime::DT\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
