.TH "example_add_api_doc" 3 "Sun Nov 30 2025 20:51:27" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example_add_api_doc \- Add Function API
.PP
 \- Adds two integers\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Adds two integers\&. 


.PP
\fBParameters\fP
.RS 4
\fIa\fP First integer operand\&. 
.br
\fIb\fP Second integer operand\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Sum of a and b\&. 
.RE
.PP
\fBNote\fP
.RS 4
Does not handle overflow\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
