.TH "Graphics" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graphics \- 基本图形  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
基本图形 

包含所有基本图形，如：点、线段、矩形、椭圆等基本图形。 
.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
