.TH "RGBAColor" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBAColor \- Predefined colors, named in RGBA format\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Predefined colors, named in RGBA format\&. 


.PP
\fBSee also\fP
.RS 4
\fBBasic\&.h\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
