.TH "D:/Coding/S3GF/src/Utils/RGBAColor.h" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Utils/RGBAColor.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Libs\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace\&. "
.ti -1c
.RI "namespace \fBS3GF::RGBAColor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBS3GF::RGBAColor::Color2RGBAValue\fP (const SDL_Color &color, bool alpha_enabled=false)"
.br
.ti -1c
.RI "SDL_Color \fBS3GF::RGBAColor::RGBAValue2Color\fP (uint64_t color_value, bool alpha_enabled=false)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
