.TH "S3GF::Matrix2D< T >::Position" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Matrix2D< T >::Position
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPosition\fP ()"
.br
.ti -1c
.RI "\fBPosition\fP (uint32_t \fBrow\fP, uint32_t \fBcol\fP)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBPosition\fP &p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBrow\fP"
.br
.ti -1c
.RI "uint32_t \fBcol\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Position::Position ()\fR [inline]\fP"

.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Position::Position (uint32_t row, uint32_t col)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::isValid () const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator!= (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator< (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator<= (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator== (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator> (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator>= (const \fBPosition\fP & p) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T> uint32_t \fBS3GF::Matrix2D\fP< T >::Position::col"

.SS "template<typename T> uint32_t \fBS3GF::Matrix2D\fP< T >::Position::row"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
