.TH "S3GF::Graphics::Line" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Graphics::Line
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLine\fP ()"
.br
.ti -1c
.RI "\fBLine\fP (float x1, float y1, float x2, float y2, uint16_t \fBsize\fP, const SDL_Color &\fBcolor\fP)"
.br
.ti -1c
.RI "\fBLine\fP (const \fBVector2\fP &start, const \fBVector2\fP &end, uint16_t \fBsize\fP, const SDL_Color &\fBcolor\fP)"
.br
.ti -1c
.RI "const int * \fBindices\fP ()"
.br
.ti -1c
.RI "const SDL_Vertex * \fBvertices\fP ()"
.br
.ti -1c
.RI "size_t \fBindicesCount\fP () const"
.br
.ti -1c
.RI "size_t \fBvertexCount\fP () const"
.br
.ti -1c
.RI "const \fBVector2\fP & \fBstartPosition\fP () const"
.br
.ti -1c
.RI "const \fBVector2\fP & \fBendPosition\fP () const"
.br
.ti -1c
.RI "void \fBsetStartPosition\fP (const \fBVector2\fP &pos)"
.br
.ti -1c
.RI "void \fBsetStartPosition\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBsetEndPosition\fP (const \fBVector2\fP &pos)"
.br
.ti -1c
.RI "void \fBsetEndPosition\fP (float x, float y)"
.br
.ti -1c
.RI "uint8_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBsetSize\fP (uint8_t new_size)"
.br
.ti -1c
.RI "const SDL_Color & \fBcolor\fP () const"
.br
.ti -1c
.RI "void \fBsetColor\fP (const SDL_Color &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBreset\fP (float sx, float sy, float ex, float ey, uint8_t \fBsize\fP, const SDL_Color &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBreset\fP (const \fBVector2\fP &start, const \fBVector2\fP &end, uint8_t \fBsize\fP, const SDL_Color &\fBcolor\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::Graphics::Line::Line ()\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::Graphics::Line::Line (float x1, float y1, float x2, float y2, uint16_t size, const SDL_Color & color)\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::Graphics::Line::Line (const \fBVector2\fP & start, const \fBVector2\fP & end, uint16_t size, const SDL_Color & color)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const SDL_Color & S3GF::Graphics::Line::color () const\fR [inline]\fP"

.SS "const \fBVector2\fP & S3GF::Graphics::Line::endPosition () const\fR [inline]\fP"

.SS "const int * S3GF::Graphics::Line::indices ()\fR [inline]\fP"

.SS "size_t S3GF::Graphics::Line::indicesCount () const\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::reset (const \fBVector2\fP & start, const \fBVector2\fP & end, uint8_t size, const SDL_Color & color)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::reset (float sx, float sy, float ex, float ey, uint8_t size, const SDL_Color & color)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::setColor (const SDL_Color & color)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::setEndPosition (const \fBVector2\fP & pos)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::setEndPosition (float x, float y)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::setSize (uint8_t new_size)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::setStartPosition (const \fBVector2\fP & pos)\fR [inline]\fP"

.SS "void S3GF::Graphics::Line::setStartPosition (float x, float y)\fR [inline]\fP"

.SS "uint8_t S3GF::Graphics::Line::size () const\fR [inline]\fP"

.SS "const \fBVector2\fP & S3GF::Graphics::Line::startPosition () const\fR [inline]\fP"

.SS "size_t S3GF::Graphics::Line::vertexCount () const\fR [inline]\fP"

.SS "const SDL_Vertex * S3GF::Graphics::Line::vertices ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
