.TH "S3GF::GeometryF" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::GeometryF \- 位置、大小  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeometryF\fP (float x, float y, float w, float h)"
.br
.ti -1c
.RI "\fBGeometryF\fP (const \fBVector2\fP &\fBpos\fP, const \fBSize\fP &\fBsize\fP)"
.br
.ti -1c
.RI "\fBGeometryF\fP (\fBVector2\fP &&\fBpos\fP, \fBSize\fP &&\fBsize\fP)"
.br
.ti -1c
.RI "\fBGeometryF\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (const \fBVector2\fP &\fBpos\fP, const \fBSize\fP &\fBsize\fP)"
.br
.ti -1c
.RI "void \fBreset\fP (float x, float y, float width, float height)"
.br
.ti -1c
.RI "void \fBreset\fP (const \fBGeometryF\fP &geometry)"
.br
.ti -1c
.RI "void \fBresetPos\fP (const \fBVector2\fP &\fBpos\fP)"
.br
.ti -1c
.RI "void \fBresetSize\fP (const \fBSize\fP &\fBsize\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector2\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBSize\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
位置、大小 

针对于 \fBVector2\fP 和 \fBSize\fP 组成，用于调整位置、大小 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::GeometryF::GeometryF (float x, float y, float w, float h)\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::GeometryF::GeometryF (const \fBVector2\fP & pos, const \fBSize\fP & size)\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::GeometryF::GeometryF (\fBVector2\fP && pos, \fBSize\fP && size)\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::GeometryF::GeometryF ()\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void S3GF::GeometryF::reset (const \fBGeometryF\fP & geometry)\fR [inline]\fP"

.SS "void S3GF::GeometryF::reset (const \fBVector2\fP & pos, const \fBSize\fP & size)\fR [inline]\fP"

.SS "void S3GF::GeometryF::reset (float x, float y, float width, float height)\fR [inline]\fP"

.SS "void S3GF::GeometryF::resetPos (const \fBVector2\fP & pos)\fR [inline]\fP"

.SS "void S3GF::GeometryF::resetSize (const \fBSize\fP & size)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector2\fP S3GF::GeometryF::pos"

.SS "\fBSize\fP S3GF::GeometryF::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
