.TH "S3GF::Graphics" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Graphics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEllipse\fP"
.br
.ti -1c
.RI "class \fBLine\fP"
.br
.ti -1c
.RI "class \fBPoint\fP"
.br
.ti -1c
.RI "class \fBRectangle\fP"
.br
.ti -1c
.RI "class \fBTriangle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
