.TH "S3GF::TextureButton::TextureStatus" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TextureButton::TextureStatus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Button\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTexture\fP * \fBnormal\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBactive\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBpressed\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBinvalid\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBchecked\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::active"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::checked"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::invalid"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::normal"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::pressed"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
