.TH "S3GF::Logger" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Logger
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Logger\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLogLevel\fP { \fBDEBUG\fP, \fBINFO\fP, \fBWARN\fP, \fBERROR\fP, \fBFATAL\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP ()=delete"
.br
.ti -1c
.RI "\fBLogger\fP (\fBLogger\fP &&)=delete"
.br
.ti -1c
.RI "\fBLogger\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (\fBLogger\fP &&)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fB~Logger\fP ()=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlog\fP (const std::string &message, \fBLogLevel\fP level=\fBDEBUG\fP)"
.br
.ti -1c
.RI "static void \fBsetBaseLogLevel\fP (\fBLogLevel\fP level)"
.br
.ti -1c
.RI "static std::string \fBlastError\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBS3GF::Logger::LogLevel\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIDEBUG \fP
.TP
\f(BIINFO \fP
.TP
\f(BIWARN \fP
.TP
\f(BIERROR \fP
.TP
\f(BIFATAL \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::Logger::Logger ()\fR [delete]\fP"

.SS "S3GF::Logger::Logger (\fBLogger\fP && )\fR [delete]\fP"

.SS "S3GF::Logger::Logger (const \fBLogger\fP & )\fR [delete]\fP"

.SS "S3GF::Logger::~Logger ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string S3GF::Logger::lastError ()\fR [inline]\fP, \fR [static]\fP"

.SS "void S3GF::Logger::log (const std::string & message, \fBLogLevel\fP level = \fR\fBDEBUG\fP\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBLogger\fP & S3GF::Logger::operator= (const \fBLogger\fP & )\fR [delete]\fP"

.SS "\fBLogger\fP & S3GF::Logger::operator= (\fBLogger\fP && )\fR [delete]\fP"

.SS "void S3GF::Logger::setBaseLogLevel (\fBLogLevel\fP level)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
