.TH "S3GF::Button::ButtonSkin" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Button::ButtonSkin
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Button\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColorStatus\fP \fBborder\fP"
.br
.ti -1c
.RI "\fBColorStatus\fP \fBbackground\fP"
.br
.ti -1c
.RI "\fBColorStatus\fP \fBfont\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBColorStatus\fP S3GF::Button::ButtonSkin::background"

.SS "\fBColorStatus\fP S3GF::Button::ButtonSkin::border"

.SS "\fBColorStatus\fP S3GF::Button::ButtonSkin::font"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
