.TH "S3GF::AudioSystem::Audio" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::AudioSystem::Audio
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MIX_Audio * \fBself\fP"
.br
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "std::string \fBurl\fP"
.br
.ti -1c
.RI "bool \fBis_stream\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   MIX_Track * \fBself\fP {nullptr}"
.br
.ti -1c
.RI "   uint64_t \fBduration\fP"
.br
.ti -1c
.RI "   uint64_t \fBposition\fP"
.br
.ti -1c
.RI "} \fBtrack\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint64_t S3GF::AudioSystem::Audio::duration"

.SS "bool S3GF::AudioSystem::Audio::is_stream"

.SS "uint64_t S3GF::AudioSystem::Audio::position"

.SS "MIX_Audio* S3GF::AudioSystem::Audio::self"

.SS "MIX_Track* S3GF::AudioSystem::Audio::self {nullptr}"

.SS "\fBStatus\fP S3GF::AudioSystem::Audio::status"

.SS "union  { \&.\&.\&. }  S3GF::AudioSystem::Audio::track"

.SS "std::string S3GF::AudioSystem::Audio::url"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
