.TH "S3GF::RandomGenerator" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::RandomGenerator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Random\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomGenerator\fP ()=delete"
.br
.ti -1c
.RI "\fBRandomGenerator\fP (\fBRandomGenerator\fP &&)=delete"
.br
.ti -1c
.RI "\fBRandomGenerator\fP (const \fBRandomGenerator\fP &)=delete"
.br
.ti -1c
.RI "\fBRandomGenerator\fP & \fBoperator=\fP (\fBRandomGenerator\fP &&)=delete"
.br
.ti -1c
.RI "\fBRandomGenerator\fP & \fBoperator=\fP (const \fBRandomGenerator\fP &)=delete"
.br
.ti -1c
.RI "\fB~RandomGenerator\fP ()=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBrandInt\fP (int start, int end)"
.br
.ti -1c
.RI "static int64_t \fBrandBigInt\fP (int64_t start, int64_t end)"
.br
.ti -1c
.RI "static uint32_t \fBrandUInt\fP (uint32_t start, uint32_t end)"
.br
.ti -1c
.RI "static uint64_t \fBrandBigUInt\fP (uint64_t start, uint64_t end)"
.br
.ti -1c
.RI "static float \fBrandFloat\fP (float start, float end)"
.br
.ti -1c
.RI "static double \fBrandDouble\fP (double start, double end)"
.br
.ti -1c
.RI "static long double \fBrandBigDouble\fP (long double start, long double end)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::random_device \fB_rnd_dev\fP {}"
.br
.ti -1c
.RI "static std::default_random_engine \fB_def_rand_eng\fP {}"
.br
.ti -1c
.RI "static bool \fB_is_init\fP {false}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::RandomGenerator::RandomGenerator ()\fR [delete]\fP"

.SS "S3GF::RandomGenerator::RandomGenerator (\fBRandomGenerator\fP && )\fR [delete]\fP"

.SS "S3GF::RandomGenerator::RandomGenerator (const \fBRandomGenerator\fP & )\fR [delete]\fP"

.SS "S3GF::RandomGenerator::~RandomGenerator ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBRandomGenerator\fP & S3GF::RandomGenerator::operator= (const \fBRandomGenerator\fP & )\fR [delete]\fP"

.SS "\fBRandomGenerator\fP & S3GF::RandomGenerator::operator= (\fBRandomGenerator\fP && )\fR [delete]\fP"

.SS "long double S3GF::RandomGenerator::randBigDouble (long double start, long double end)\fR [inline]\fP, \fR [static]\fP"

.SS "int64_t S3GF::RandomGenerator::randBigInt (int64_t start, int64_t end)\fR [inline]\fP, \fR [static]\fP"

.SS "uint64_t S3GF::RandomGenerator::randBigUInt (uint64_t start, uint64_t end)\fR [inline]\fP, \fR [static]\fP"

.SS "double S3GF::RandomGenerator::randDouble (double start, double end)\fR [inline]\fP, \fR [static]\fP"

.SS "float S3GF::RandomGenerator::randFloat (float start, float end)\fR [inline]\fP, \fR [static]\fP"

.SS "int S3GF::RandomGenerator::randInt (int start, int end)\fR [inline]\fP, \fR [static]\fP"

.SS "uint32_t S3GF::RandomGenerator::randUInt (uint32_t start, uint32_t end)\fR [inline]\fP, \fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::default_random_engine S3GF::RandomGenerator::_def_rand_eng {}\fR [inline]\fP, \fR [static]\fP"

.SS "bool S3GF::RandomGenerator::_is_init {false}\fR [inline]\fP, \fR [static]\fP"

.SS "std::random_device S3GF::RandomGenerator::_rnd_dev {}\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
