.TH "S3GF::AudioSystem" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::AudioSystem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAudio\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBStatus\fP { \fBUnknown\fP, \fBNoLoaded\fP, \fBLoading\fP, \fBInvalid\fP, \fBLoaded\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioSystem\fP (\fBAudioSystem\fP &&)=delete"
.br
.ti -1c
.RI "\fBAudioSystem\fP (const \fBAudioSystem\fP &)=delete"
.br
.ti -1c
.RI "\fBAudioSystem\fP & \fBoperator=\fP (\fBAudioSystem\fP &&)=delete"
.br
.ti -1c
.RI "\fBAudioSystem\fP & \fBoperator=\fP (const \fBAudioSystem\fP &)=delete"
.br
.ti -1c
.RI "\fB~AudioSystem\fP ()"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBload\fP ()"
.br
.ti -1c
.RI "void \fBunload\fP ()"
.br
.ti -1c
.RI "uint64_t \fBnewAudio\fP ()"
.br
.ti -1c
.RI "bool \fBremove\fP (uint64_t audio_id)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "const \fBAudio\fP & \fBaudio\fP (uint64_t audio_id) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAudioSystem\fP * \fBglobal\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBS3GF::AudioSystem::Status\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIUnknown \fP
.TP
\f(BINoLoaded \fP
.TP
\f(BILoading \fP
.TP
\f(BIInvalid \fP
.TP
\f(BILoaded \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::AudioSystem::AudioSystem (\fBAudioSystem\fP && )\fR [delete]\fP"

.SS "S3GF::AudioSystem::AudioSystem (const \fBAudioSystem\fP & )\fR [delete]\fP"

.SS "S3GF::AudioSystem::~AudioSystem ()"

.SH "Member Function Documentation"
.PP 
.SS "const \fBAudio\fP & S3GF::AudioSystem::audio (uint64_t audio_id) const"

.SS "void S3GF::AudioSystem::clear ()"

.SS "\fBAudioSystem\fP * S3GF::AudioSystem::global ()\fR [static]\fP"

.SS "bool S3GF::AudioSystem::isValid () const"

.SS "bool S3GF::AudioSystem::load ()"

.SS "uint64_t S3GF::AudioSystem::newAudio ()"

.SS "\fBAudioSystem\fP & S3GF::AudioSystem::operator= (\fBAudioSystem\fP && )\fR [delete]\fP"

.SS "\fBAudioSystem\fP & S3GF::AudioSystem::operator= (const \fBAudioSystem\fP & )\fR [delete]\fP"

.SS "bool S3GF::AudioSystem::remove (uint64_t audio_id)"

.SS "void S3GF::AudioSystem::unload ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
