.TH "S3GF::FontDatabase::FontInfo" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::FontDatabase::FontInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfont_name\fP"
.br
.ti -1c
.RI "std::string \fBfont_path\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string S3GF::FontDatabase::FontInfo::font_name"

.SS "std::string S3GF::FontDatabase::FontInfo::font_path"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
