.TH "S3GF::Trigger" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Trigger
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Components\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrigger\fP ()=delete"
.br
.ti -1c
.RI "\fBTrigger\fP (\fBTrigger\fP &&)=delete"
.br
.ti -1c
.RI "\fBTrigger\fP (const \fBTrigger\fP &)=delete"
.br
.ti -1c
.RI "\fBTrigger\fP & \fBoperator=\fP (\fBTrigger\fP &&)=delete"
.br
.ti -1c
.RI "\fBTrigger\fP & \fBoperator=\fP (const \fBTrigger\fP &)=delete"
.br
.ti -1c
.RI "\fBTrigger\fP (const std::function< bool()> &condition, const std::function< void()> &event)"
.br
.ti -1c
.RI "\fB~Trigger\fP ()"
.br
.ti -1c
.RI "void \fBsetCondition\fP (const std::function< bool()> &condition)"
.br
.ti -1c
.RI "void \fBsetEvent\fP (const std::function< void()> &event)"
.br
.ti -1c
.RI "void \fBstart\fP (uint32_t count=1)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "bool \fBenabled\fP () const"
.br
.ti -1c
.RI "bool \fBisTriggered\fP () const"
.br
.ti -1c
.RI "uint64_t \fBtriggeredCount\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::Trigger::Trigger ()\fR [delete]\fP"

.SS "S3GF::Trigger::Trigger (\fBTrigger\fP && )\fR [delete]\fP"

.SS "S3GF::Trigger::Trigger (const \fBTrigger\fP & )\fR [delete]\fP"

.SS "S3GF::Trigger::Trigger (const std::function< bool()> & condition, const std::function< void()> & event)\fR [explicit]\fP"

.SS "S3GF::Trigger::~Trigger ()"

.SH "Member Function Documentation"
.PP 
.SS "bool S3GF::Trigger::enabled () const"

.SS "bool S3GF::Trigger::isTriggered () const"

.SS "\fBTrigger\fP & S3GF::Trigger::operator= (const \fBTrigger\fP & )\fR [delete]\fP"

.SS "\fBTrigger\fP & S3GF::Trigger::operator= (\fBTrigger\fP && )\fR [delete]\fP"

.SS "void S3GF::Trigger::setCondition (const std::function< bool()> & condition)"

.SS "void S3GF::Trigger::setEvent (const std::function< void()> & event)"

.SS "void S3GF::Trigger::start (uint32_t count = \fR1\fP)"

.SS "void S3GF::Trigger::stop ()"

.SS "uint64_t S3GF::Trigger::triggeredCount () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
