.TH "S3GF::TasksManager::Task" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TasksManager::Task
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ThreadPool\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "\fBPriority\fP \fBpriority\fP"
.br
.ti -1c
.RI "std::function< void()> \fBfunction\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::function<void()> S3GF::TasksManager::Task::function"

.SS "uint64_t S3GF::TasksManager::Task::id"

.SS "\fBPriority\fP S3GF::TasksManager::Task::priority"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
