.TH "S3GF::TasksManager" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TasksManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ThreadPool\&.h>\fP
.PP
Inherits \fBS3GF::ThreadPool\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTask\fP"
.br
.ti -1c
.RI "struct \fBTaskCmp\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPriority\fP { \fBLow\fP, \fBMedium\fP, \fBHigh\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTasksManager\fP (size_t max_tasks, size_t max_threads)"
.br
.ti -1c
.RI "void \fBaddTask\fP (std::function< void()> function, \fBPriority\fP priority=\fBLow\fP)"
.br
.ti -1c
.RI "void \fBstartAllTasks\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstopAllTasks\fP ()"
.br
.ti -1c
.RI "void \fBwait\fP ()"
.br
.ti -1c
.RI "size_t \fBtasksCount\fP () const"
.br
.ti -1c
.RI "size_t \fBrunningTasks\fP () const"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBS3GF::TasksManager::Priority\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILow \fP
.TP
\f(BIMedium \fP
.TP
\f(BIHigh \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::TasksManager::TasksManager (size_t max_tasks, size_t max_threads)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void S3GF::TasksManager::addTask (std::function< void()> function, \fBPriority\fP priority = \fR\fBLow\fP\fP)\fR [inline]\fP"

.SS "size_t S3GF::TasksManager::runningTasks () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "void S3GF::TasksManager::start ()\fR [inline]\fP"

.SS "void S3GF::TasksManager::startAllTasks ()\fR [inline]\fP"

.SS "void S3GF::TasksManager::stopAllTasks ()\fR [inline]\fP"

.SS "size_t S3GF::TasksManager::tasksCount () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "void S3GF::TasksManager::wait ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
