.TH "S3GF::TextureButton" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TextureButton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Button\&.h>\fP
.PP
Inherits \fBS3GF::AbstractControl\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTextureStatus\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureButton\fP (const std::string &\fBname\fP, \fBRenderer\fP *renderer, \fBAbstractControl\fP *parent=nullptr)"
.br
.ti -1c
.RI "\fB~TextureButton\fP ()"
.br
.ti -1c
.RI "void \fBsetTextures\fP (\fBTexture\fP *normal, \fBTexture\fP *\fBactive\fP=nullptr, \fBTexture\fP *pressed=nullptr, \fBTexture\fP *invalid=nullptr, \fBTexture\fP *checked=nullptr)"
.br
.ti -1c
.RI "void \fBsetFont\fP (const std::string &font_name, const std::string &font_path={})"
.br
.ti -1c
.RI "const std::string & \fBfontName\fP () const"
.br
.ti -1c
.RI "void \fBsetText\fP (const std::string &\fBtext\fP)"
.br
.ti -1c
.RI "const std::string & \fBtext\fP () const"
.br
.ti -1c
.RI "\fBSize\fP \fBtextSize\fP () const"
.br
.ti -1c
.RI "void \fBsetTextVisible\fP (bool \fBvisible\fP)"
.br
.ti -1c
.RI "bool \fBisTextVisible\fP () const"
.br
.ti -1c
.RI "void \fBsetTextPosition\fP (const \fBVector2\fP &pos)"
.br
.ti -1c
.RI "const \fBVector2\fP & \fBtextPosition\fP () const"
.br
.ti -1c
.RI "\fBColorStatus\fP & \fBtextColor\fP ()"
.br
.ti -1c
.RI "void \fBsetEvent\fP (const std::function< void()> &event)"
.br
.in -1c

Public Member Functions inherited from \fBS3GF::AbstractControl\fP
.in +1c
.ti -1c
.RI "\fBAbstractControl\fP (const std::string &\fBname\fP, \fBRenderer\fP *renderer, \fBAbstractControl\fP *parent=nullptr, \fBGT\fP click_area=\fBGraphics::Rectangle\fP())"
.br
.ti -1c
.RI "\fB~AbstractControl\fP ()=default"
.br
.ti -1c
.RI "void \fBsetName\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "void \fBmove\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBmove\fP (const \fBVector2\fP &pos)"
.br
.ti -1c
.RI "void \fBmove\fP (\fBVector2\fP &&pos)"
.br
.ti -1c
.RI "void \fBresize\fP (float w, float h)"
.br
.ti -1c
.RI "void \fBresize\fP (const \fBSize\fP &\fBsize\fP)"
.br
.ti -1c
.RI "void \fBresize\fP (\fBSize\fP &&\fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (float x, float y, float w, float h)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (const \fBVector2\fP &pos, const \fBSize\fP &\fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (\fBVector2\fP &&pos, \fBSize\fP &&\fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (const \fBGeometryF\fP &\fBgeometry\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (\fBGeometryF\fP &&\fBgeometry\fP)"
.br
.ti -1c
.RI "const \fBGeometryF\fP & \fBgeometry\fP () const"
.br
.ti -1c
.RI "const \fBVector2\fP & \fBposition\fP () const"
.br
.ti -1c
.RI "const \fBSize\fP & \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool \fBvisible\fP)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool \fBenabled\fP)"
.br
.ti -1c
.RI "bool \fBenabled\fP () const"
.br
.ti -1c
.RI "void \fBsetActive\fP ()"
.br
.ti -1c
.RI "void \fBsetInactive\fP ()"
.br
.ti -1c
.RI "bool \fBactive\fP () const"
.br
.ti -1c
.RI "void \fBsetKey\fP (SDL_Keycode key)"
.br
.ti -1c
.RI "void \fBsetCheckable\fP (bool \fBcheckable\fP)"
.br
.ti -1c
.RI "void \fBsetChecked\fP (bool checked)"
.br
.ti -1c
.RI "bool \fBcheckable\fP () const"
.br
.ti -1c
.RI "bool \fBisChecked\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonEntered\fP () override"
.br
.ti -1c
.RI "void \fBonHovered\fP () override"
.br
.ti -1c
.RI "void \fBonLeft\fP () override"
.br
.ti -1c
.RI "void \fBonPressed\fP () override"
.br
.ti -1c
.RI "void \fBonReleased\fP () override"
.br
.ti -1c
.RI "void \fBonTriggered\fP () override"
.br
.ti -1c
.RI "void \fBonKeyPressed\fP () override"
.br
.ti -1c
.RI "void \fBonKeyReleased\fP () override"
.br
.ti -1c
.RI "void \fBresizeEvent\fP () override"
.br
.ti -1c
.RI "void \fBmoveEvent\fP () override"
.br
.ti -1c
.RI "void \fBonChecked\fP (bool checked) override"
.br
.ti -1c
.RI "void \fBenabledChanged\fP (bool \fBenabled\fP) override"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (\fBRenderer\fP *r) override"
.br
.in -1c

Protected Member Functions inherited from \fBS3GF::AbstractControl\fP
.in +1c
.ti -1c
.RI "virtual void \fBactiveChanged\fP (bool \fBactive\fP)"
.br
.ti -1c
.RI "virtual void \fBvisibleChanged\fP (bool \fBvisible\fP)"
.br
.ti -1c
.RI "void \fB_update_click_area\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBS3GF::AbstractControl\fP
.in +1c
.ti -1c
.RI "uint64_t \fB_id\fP {0}"
.br
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "\fBRenderer\fP * \fB_renderer\fP"
.br
.ti -1c
.RI "\fBAbstractControl\fP * \fB_parent\fP"
.br
.ti -1c
.RI "\fBGeometryF\fP \fB_geometry\fP"
.br
.ti -1c
.RI "\fBClickArea\fP \fB_click_area\fP"
.br
.ti -1c
.RI "SDL_Keycode \fB_key_code\fP {SDLK_UNKNOWN}"
.br
.ti -1c
.RI "bool \fB_is_down\fP {false}"
.br
.ti -1c
.RI "bool \fB_is_hovered\fP {false}"
.br
.ti -1c
.RI "bool \fB_is_checked\fP {false}"
.br
.ti -1c
.RI "bool \fB_visible\fP {true}"
.br
.ti -1c
.RI "bool \fB_enabled\fP {true}"
.br
.ti -1c
.RI "bool \fB_entered\fP {false}"
.br
.ti -1c
.RI "bool \fB_active\fP {false}"
.br
.ti -1c
.RI "bool \fB_checkable\fP {false}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::TextureButton::TextureButton (const std::string & name, \fBRenderer\fP * renderer, \fBAbstractControl\fP * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SS "S3GF::TextureButton::~TextureButton ()"

.SH "Member Function Documentation"
.PP 
.SS "void S3GF::TextureButton::enabledChanged (bool enabled)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "const std::string & S3GF::TextureButton::fontName () const\fR [nodiscard]\fP"

.SS "bool S3GF::TextureButton::isTextVisible () const\fR [nodiscard]\fP"

.SS "void S3GF::TextureButton::moveEvent ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onChecked (bool checked)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onEntered ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onHovered ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onKeyPressed ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onKeyReleased ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onLeft ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onPressed ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onReleased ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::onTriggered ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::paintEvent (\fBRenderer\fP * r)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::resizeEvent ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBS3GF::AbstractControl\fP\&.
.SS "void S3GF::TextureButton::setEvent (const std::function< void()> & event)"

.SS "void S3GF::TextureButton::setFont (const std::string & font_name, const std::string & font_path = \fR{}\fP)"

.SS "void S3GF::TextureButton::setText (const std::string & text)"

.SS "void S3GF::TextureButton::setTextPosition (const \fBVector2\fP & pos)"

.SS "void S3GF::TextureButton::setTextures (\fBTexture\fP * normal, \fBTexture\fP * active = \fRnullptr\fP, \fBTexture\fP * pressed = \fRnullptr\fP, \fBTexture\fP * invalid = \fRnullptr\fP, \fBTexture\fP * checked = \fRnullptr\fP)"

.SS "void S3GF::TextureButton::setTextVisible (bool visible)"

.SS "const std::string & S3GF::TextureButton::text () const\fR [nodiscard]\fP"

.SS "\fBColorStatus\fP & S3GF::TextureButton::textColor ()\fR [nodiscard]\fP"

.SS "const \fBVector2\fP & S3GF::TextureButton::textPosition () const\fR [nodiscard]\fP"

.SS "\fBSize\fP S3GF::TextureButton::textSize () const\fR [nodiscard]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
