.TH "S3GF::TextSystem::FontEngine" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TextSystem::FontEngine
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TTF_TextEngine * \fBengine\fP"
.br
.ti -1c
.RI "TTF_TextEngine * \fBsurface_engine\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBFont\fP > \fBfont\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "TTF_TextEngine* S3GF::TextSystem::FontEngine::engine"

.SS "std::shared_ptr<\fBFont\fP> S3GF::TextSystem::FontEngine::font"

.SS "TTF_TextEngine* S3GF::TextSystem::FontEngine::surface_engine"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
