.TH "S3GF::FontDatabase" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::FontDatabase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFontInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFontDatabase\fP ()=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP (const \fBFontDatabase\fP &)=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP (\fBFontDatabase\fP &&)=delete"
.br
.ti -1c
.RI "\fB~FontDatabase\fP ()=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP & \fBoperator=\fP (const \fBFontDatabase\fP &)=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP & \fBoperator=\fP (\fBFontDatabase\fP &&)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFontMap\fP \fBgetFontDatabaseFromSystem\fP ()"
.br
.ti -1c
.RI "static std::string \fBfindFontFromSystem\fP (const std::string &font_name)"
.br
.ti -1c
.RI "static std::vector< \fBFontInfo\fP > \fBgetSystemDefaultFont\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::FontDatabase::FontDatabase ()\fR [delete]\fP"

.SS "S3GF::FontDatabase::FontDatabase (const \fBFontDatabase\fP & )\fR [delete]\fP"

.SS "S3GF::FontDatabase::FontDatabase (\fBFontDatabase\fP && )\fR [delete]\fP"

.SS "S3GF::FontDatabase::~FontDatabase ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string S3GF::FontDatabase::findFontFromSystem (const std::string & font_name)\fR [static]\fP"

.SS "\fBFontMap\fP S3GF::FontDatabase::getFontDatabaseFromSystem ()\fR [static]\fP"

.SS "std::vector< \fBFontDatabase::FontInfo\fP > S3GF::FontDatabase::getSystemDefaultFont ()\fR [static]\fP"

.SS "\fBFontDatabase\fP & S3GF::FontDatabase::operator= (const \fBFontDatabase\fP & )\fR [delete]\fP"

.SS "\fBFontDatabase\fP & S3GF::FontDatabase::operator= (\fBFontDatabase\fP && )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
