.TH "S3GF::ColorStatus" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::ColorStatus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Control\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_Color \fBnormal\fP"
.br
.ti -1c
.RI "SDL_Color \fBactive\fP"
.br
.ti -1c
.RI "SDL_Color \fBpressed\fP"
.br
.ti -1c
.RI "SDL_Color \fBinvalid\fP"
.br
.ti -1c
.RI "SDL_Color \fBchecked\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "SDL_Color S3GF::ColorStatus::active"

.SS "SDL_Color S3GF::ColorStatus::checked"

.SS "SDL_Color S3GF::ColorStatus::invalid"

.SS "SDL_Color S3GF::ColorStatus::normal"

.SS "SDL_Color S3GF::ColorStatus::pressed"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
