.TH "S3GF::Timer" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Timer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Components\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimer\fP ()=delete"
.br
.ti -1c
.RI "\fBTimer\fP (\fBTimer\fP &&)=delete"
.br
.ti -1c
.RI "\fBTimer\fP (const \fBTimer\fP &)=delete"
.br
.ti -1c
.RI "\fBTimer\fP & \fBoperator=\fP (\fBTimer\fP &&)=delete"
.br
.ti -1c
.RI "\fBTimer\fP & \fBoperator=\fP (const \fBTimer\fP &)=delete"
.br
.ti -1c
.RI "\fB~Timer\fP ()"
.br
.ti -1c
.RI "\fBTimer\fP (uint64_t \fBdelay\fP, const std::function< void()> &event)"
.br
.ti -1c
.RI "void \fBsetDelay\fP (uint64_t \fBdelay\fP)"
.br
.ti -1c
.RI "void \fBstart\fP (uint32_t count=1)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "bool \fBenabled\fP () const"
.br
.ti -1c
.RI "uint64_t \fBdelay\fP () const"
.br
.ti -1c
.RI "void \fBsetEvent\fP (const std::function< void()> &event)"
.br
.ti -1c
.RI "bool \fBisFinished\fP () const"
.br
.ti -1c
.RI "uint32_t \fBtriggeredCount\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::Timer::Timer ()\fR [delete]\fP"

.SS "S3GF::Timer::Timer (\fBTimer\fP && )\fR [delete]\fP"

.SS "S3GF::Timer::Timer (const \fBTimer\fP & )\fR [delete]\fP"

.SS "S3GF::Timer::~Timer ()"

.SS "S3GF::Timer::Timer (uint64_t delay, const std::function< void()> & event)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint64_t S3GF::Timer::delay () const"

.SS "bool S3GF::Timer::enabled () const"

.SS "bool S3GF::Timer::isFinished () const"

.SS "\fBTimer\fP & S3GF::Timer::operator= (const \fBTimer\fP & )\fR [delete]\fP"

.SS "\fBTimer\fP & S3GF::Timer::operator= (\fBTimer\fP && )\fR [delete]\fP"

.SS "void S3GF::Timer::setDelay (uint64_t delay)"

.SS "void S3GF::Timer::setEvent (const std::function< void()> & event)"

.SS "void S3GF::Timer::start (uint32_t count = \fR1\fP)"

.SS "void S3GF::Timer::stop ()"

.SS "uint32_t S3GF::Timer::triggeredCount () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
