.TH "S3GF::AbstractControl" 3 "Sun Nov 30 2025 21:10:40" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::AbstractControl
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Control\&.h>\fP
.PP
Inherited by \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractControl\fP (const std::string &\fBname\fP, \fBRenderer\fP *renderer, \fBAbstractControl\fP *parent=nullptr, \fBGT\fP click_area=\fBGraphics::Rectangle\fP())"
.br
.ti -1c
.RI "\fB~AbstractControl\fP ()=default"
.br
.ti -1c
.RI "void \fBsetName\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "void \fBmove\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBmove\fP (const \fBVector2\fP &pos)"
.br
.ti -1c
.RI "void \fBmove\fP (\fBVector2\fP &&pos)"
.br
.ti -1c
.RI "void \fBresize\fP (float w, float h)"
.br
.ti -1c
.RI "void \fBresize\fP (const \fBSize\fP &\fBsize\fP)"
.br
.ti -1c
.RI "void \fBresize\fP (\fBSize\fP &&\fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (float x, float y, float w, float h)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (const \fBVector2\fP &pos, const \fBSize\fP &\fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (\fBVector2\fP &&pos, \fBSize\fP &&\fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (const \fBGeometryF\fP &\fBgeometry\fP)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (\fBGeometryF\fP &&\fBgeometry\fP)"
.br
.ti -1c
.RI "const \fBGeometryF\fP & \fBgeometry\fP () const"
.br
.ti -1c
.RI "const \fBVector2\fP & \fBposition\fP () const"
.br
.ti -1c
.RI "const \fBSize\fP & \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBsetVisible\fP (bool \fBvisible\fP)"
.br
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool \fBenabled\fP)"
.br
.ti -1c
.RI "bool \fBenabled\fP () const"
.br
.ti -1c
.RI "void \fBsetActive\fP ()"
.br
.ti -1c
.RI "void \fBsetInactive\fP ()"
.br
.ti -1c
.RI "bool \fBactive\fP () const"
.br
.ti -1c
.RI "void \fBsetKey\fP (SDL_Keycode key)"
.br
.ti -1c
.RI "void \fBsetCheckable\fP (bool \fBcheckable\fP)"
.br
.ti -1c
.RI "void \fBsetChecked\fP (bool checked)"
.br
.ti -1c
.RI "bool \fBcheckable\fP () const"
.br
.ti -1c
.RI "bool \fBisChecked\fP () const"
.br
.ti -1c
.RI "bool \fBisDown\fP () const"
.br
.ti -1c
.RI "bool \fBisHovered\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (\fBRenderer\fP *)"
.br
.ti -1c
.RI "virtual void \fBmoveEvent\fP ()"
.br
.ti -1c
.RI "virtual void \fBresizeEvent\fP ()"
.br
.ti -1c
.RI "virtual void \fBonPressed\fP ()"
.br
.ti -1c
.RI "virtual void \fBonReleased\fP ()"
.br
.ti -1c
.RI "virtual void \fBonTriggered\fP ()"
.br
.ti -1c
.RI "virtual void \fBonHovered\fP ()"
.br
.ti -1c
.RI "virtual void \fBonEntered\fP ()"
.br
.ti -1c
.RI "virtual void \fBonLeft\fP ()"
.br
.ti -1c
.RI "virtual void \fBonKeyPressed\fP ()"
.br
.ti -1c
.RI "virtual void \fBonKeyReleased\fP ()"
.br
.ti -1c
.RI "virtual void \fBonChecked\fP (bool checked)"
.br
.ti -1c
.RI "virtual void \fBactiveChanged\fP (bool \fBactive\fP)"
.br
.ti -1c
.RI "virtual void \fBenabledChanged\fP (bool \fBenabled\fP)"
.br
.ti -1c
.RI "virtual void \fBvisibleChanged\fP (bool \fBvisible\fP)"
.br
.ti -1c
.RI "void \fB_update_click_area\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fB_id\fP {0}"
.br
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "\fBRenderer\fP * \fB_renderer\fP"
.br
.ti -1c
.RI "\fBAbstractControl\fP * \fB_parent\fP"
.br
.ti -1c
.RI "\fBGeometryF\fP \fB_geometry\fP"
.br
.ti -1c
.RI "\fBClickArea\fP \fB_click_area\fP"
.br
.ti -1c
.RI "SDL_Keycode \fB_key_code\fP {SDLK_UNKNOWN}"
.br
.ti -1c
.RI "bool \fB_is_down\fP {false}"
.br
.ti -1c
.RI "bool \fB_is_hovered\fP {false}"
.br
.ti -1c
.RI "bool \fB_is_checked\fP {false}"
.br
.ti -1c
.RI "bool \fB_visible\fP {true}"
.br
.ti -1c
.RI "bool \fB_enabled\fP {true}"
.br
.ti -1c
.RI "bool \fB_entered\fP {false}"
.br
.ti -1c
.RI "bool \fB_active\fP {false}"
.br
.ti -1c
.RI "bool \fB_checkable\fP {false}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::AbstractControl::AbstractControl (const std::string & name, \fBRenderer\fP * renderer, \fBAbstractControl\fP * parent = \fRnullptr\fP, \fBGT\fP click_area = \fR\fBGraphics::Rectangle\fP()\fP)\fR [explicit]\fP"

.SS "S3GF::AbstractControl::~AbstractControl ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void S3GF::AbstractControl::_update_click_area ()\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::active () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "virtual void S3GF::AbstractControl::activeChanged (bool active)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SS "bool S3GF::AbstractControl::checkable () const\fR [nodiscard]\fP"

.SS "bool S3GF::AbstractControl::enabled () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "virtual void S3GF::AbstractControl::enabledChanged (bool enabled)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "const \fBGeometryF\fP & S3GF::AbstractControl::geometry () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "bool S3GF::AbstractControl::isChecked () const\fR [nodiscard]\fP"

.SS "bool S3GF::AbstractControl::isDown () const\fR [nodiscard]\fP"

.SS "bool S3GF::AbstractControl::isHovered () const\fR [nodiscard]\fP"

.SS "void S3GF::AbstractControl::move (const \fBVector2\fP & pos)"

.SS "void S3GF::AbstractControl::move (float x, float y)"

.SS "void S3GF::AbstractControl::move (\fBVector2\fP && pos)"

.SS "virtual void S3GF::AbstractControl::moveEvent ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "const std::string & S3GF::AbstractControl::name () const\fR [nodiscard]\fP"

.SS "virtual void S3GF::AbstractControl::onChecked (bool checked)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onEntered ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onHovered ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onKeyPressed ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onKeyReleased ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onLeft ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onPressed ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onReleased ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::onTriggered ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "virtual void S3GF::AbstractControl::paintEvent (\fBRenderer\fP * )\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "const \fBVector2\fP & S3GF::AbstractControl::position () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "void S3GF::AbstractControl::resize (const \fBSize\fP & size)"

.SS "void S3GF::AbstractControl::resize (float w, float h)"

.SS "void S3GF::AbstractControl::resize (\fBSize\fP && size)"

.SS "virtual void S3GF::AbstractControl::resizeEvent ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBS3GF::Button\fP, and \fBS3GF::TextureButton\fP\&.
.SS "void S3GF::AbstractControl::setActive ()\fR [inline]\fP"

.SS "void S3GF::AbstractControl::setCheckable (bool checkable)"

.SS "void S3GF::AbstractControl::setChecked (bool checked)"

.SS "void S3GF::AbstractControl::setEnabled (bool enabled)"

.SS "void S3GF::AbstractControl::setGeometry (const \fBGeometryF\fP & geometry)"

.SS "void S3GF::AbstractControl::setGeometry (const \fBVector2\fP & pos, const \fBSize\fP & size)"

.SS "void S3GF::AbstractControl::setGeometry (float x, float y, float w, float h)"

.SS "void S3GF::AbstractControl::setGeometry (\fBGeometryF\fP && geometry)"

.SS "void S3GF::AbstractControl::setGeometry (\fBVector2\fP && pos, \fBSize\fP && size)"

.SS "void S3GF::AbstractControl::setInactive ()\fR [inline]\fP"

.SS "void S3GF::AbstractControl::setKey (SDL_Keycode key)"

.SS "void S3GF::AbstractControl::setName (const std::string & name)"

.SS "void S3GF::AbstractControl::setVisible (bool visible)"

.SS "const \fBSize\fP & S3GF::AbstractControl::size () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "bool S3GF::AbstractControl::visible () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "virtual void S3GF::AbstractControl::visibleChanged (bool visible)\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool S3GF::AbstractControl::_active {false}\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_checkable {false}\fR [protected]\fP"

.SS "\fBClickArea\fP S3GF::AbstractControl::_click_area\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_enabled {true}\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_entered {false}\fR [protected]\fP"

.SS "\fBGeometryF\fP S3GF::AbstractControl::_geometry\fR [protected]\fP"

.SS "uint64_t S3GF::AbstractControl::_id {0}\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_is_checked {false}\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_is_down {false}\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_is_hovered {false}\fR [protected]\fP"

.SS "SDL_Keycode S3GF::AbstractControl::_key_code {SDLK_UNKNOWN}\fR [protected]\fP"

.SS "std::string S3GF::AbstractControl::_name\fR [protected]\fP"

.SS "\fBAbstractControl\fP* S3GF::AbstractControl::_parent\fR [protected]\fP"

.SS "\fBRenderer\fP* S3GF::AbstractControl::_renderer\fR [protected]\fP"

.SS "bool S3GF::AbstractControl::_visible {true}\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
