.TH "S3GF" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF \- \fBS3GF\fP Namespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAlgorithm\fP"
.br
.ti -1c
.RI "namespace \fBGraphics\fP"
.br
.ti -1c
.RI "namespace \fBRGBAColor\fP"
.br
.ti -1c
.RI "namespace \fBStdColor\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractControl\fP"
.br
.ti -1c
.RI "class \fBAudioSystem\fP"
.br
.ti -1c
.RI "class \fBButton\fP"
.br
.ti -1c
.RI "class \fBClickArea\fP"
.br
.ti -1c
.RI "struct \fBColorStatus\fP"
.br
.ti -1c
.RI "class \fBCursor\fP"
.br
.RI "鼠标光标 "
.ti -1c
.RI "class \fBDateTime\fP"
.br
.ti -1c
.RI "class \fBEngine\fP"
.br
.ti -1c
.RI "class \fBEventSystem\fP"
.br
.ti -1c
.RI "class \fBFileSystem\fP"
.br
.RI "文件系统 "
.ti -1c
.RI "class \fBFont\fP"
.br
.ti -1c
.RI "class \fBFontDatabase\fP"
.br
.ti -1c
.RI "struct \fBGeometry\fP"
.br
.RI "Including position and size\&. "
.ti -1c
.RI "struct \fBGeometryF\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "struct \fBMatrix2D\fP"
.br
.RI "二维矩阵 "
.ti -1c
.RI "struct \fBProperty\fP"
.br
.ti -1c
.RI "class \fBRandomGenerator\fP"
.br
.ti -1c
.RI "class \fBRenderer\fP"
.br
.ti -1c
.RI "struct \fBSize\fP"
.br
.RI "尺寸、大小 "
.ti -1c
.RI "class \fBTaskQueue\fP"
.br
.ti -1c
.RI "class \fBTasksManager\fP"
.br
.ti -1c
.RI "class \fBTextSystem\fP"
.br
.ti -1c
.RI "class \fBTexture\fP"
.br
.ti -1c
.RI "class \fBTextureAtlas\fP"
.br
.ti -1c
.RI "class \fBTextureButton\fP"
.br
.ti -1c
.RI "class \fBThreadPool\fP"
.br
.ti -1c
.RI "class \fBTimer\fP"
.br
.ti -1c
.RI "class \fBTrigger\fP"
.br
.ti -1c
.RI "struct \fBVector2\fP"
.br
.RI "向量坐标 "
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBGT\fP = std::variant<std::monostate, \fBGraphics::Point\fP, \fBGraphics::Rectangle\fP>"
.br
.ti -1c
.RI "using \fBFontMap\fP = std::unordered_map<std::string, std::string>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGeometry\fP \fBtoGeometryInt\fP (const \fBGeometryF\fP &geo)"
.br
.ti -1c
.RI "\fBGeometryF\fP \fBtoGeometryFloat\fP (const \fBGeometry\fP &geo)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint64_t \fB_next_id\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBS3GF\fP Namespace\&. 

All libraries will be stored in this namespace\&. 
.SH "Typedef Documentation"
.PP 
.SS "using \fBS3GF::FontMap\fP = std::unordered_map<std::string, std::string>"

.SS "using \fBS3GF::GT\fP = std::variant<std::monostate, \fBGraphics::Point\fP, \fBGraphics::Rectangle\fP>"

.SH "Function Documentation"
.PP 
.SS "\fBGeometryF\fP S3GF::toGeometryFloat (const \fBGeometry\fP & geo)\fR [inline]\fP"

.SS "\fBGeometry\fP S3GF::toGeometryInt (const \fBGeometryF\fP & geo)\fR [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "uint64_t S3GF::_next_id = 0\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
