.TH "S3GF::FileSystem" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::FileSystem \- 文件系统  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FileSystem\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFilter\fP { \fBAll\fP, \fBFilesOnly\fP, \fBDirectoriesOnly\fP }"
.br
.RI "文件类型筛选 "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileSystem\fP ()=delete"
.br
.ti -1c
.RI "\fBFileSystem\fP (\fBFileSystem\fP &)=delete"
.br
.ti -1c
.RI "\fBFileSystem\fP & \fBoperator=\fP (const \fBFileSystem\fP &)=delete"
.br
.ti -1c
.RI "\fB~FileSystem\fP ()=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBsetCurrentPath\fP (const std::string &main_directory)"
.br
.RI "设置当前的目录 "
.ti -1c
.RI "static const std::string & \fBcurrentPath\fP ()"
.br
.RI "获取当前的目录 "
.ti -1c
.RI "static bool \fBisFile\fP (const std::string &path)"
.br
.RI "指定文件是否存在 "
.ti -1c
.RI "static bool \fBisDir\fP (const std::string &path)"
.br
.RI "指定一个目录是否存在？ "
.ti -1c
.RI "static bool \fBmkDir\fP (const std::string &path, bool ignore_error=false, bool recursive_create=false)"
.br
.RI "创建一个空目录 "
.ti -1c
.RI "static bool \fBrmDir\fP (const std::string &path, bool ignore_error=false, bool recursive_remove=false)"
.br
.RI "删除指定的目录 "
.ti -1c
.RI "static bool \fBmkFile\fP (const std::string &path, bool auto_create_directory=false, bool ignore_error=false)"
.br
.RI "创建一个空白文件 "
.ti -1c
.RI "static bool \fBrmFile\fP (const std::string &path, bool ignore_error=false)"
.br
.RI "删除指定的文件 "
.ti -1c
.RI "static bool \fBwriteFile\fP (const std::string &context, const std::string &path, bool append_mode, bool ignore_error=false)"
.br
.RI "写入内容到指定文件 "
.ti -1c
.RI "static std::string \fBreadFile\fP (const std::string &path, bool ignore_error=false, bool *ok=nullptr)"
.br
.RI "从指定文件中读取内容 "
.ti -1c
.RI "static bool \fBwriteBinaryFile\fP (const std::string &path, bool append_mode, const std::function< void(std::ofstream &file)> &how2WriteFile, bool ignore_error=false)"
.br
.RI "写入二进制内容到指定文件 "
.ti -1c
.RI "static bool \fBwriteBinaryFile\fP (const std::vector< uint8_t > &binaries, const std::string &path, bool append_mode, bool ignore_error=false)"
.br
.RI "写入二进制内容到指定文件中 "
.ti -1c
.RI "static bool \fBreadBinaryFile\fP (const std::string &path, const std::function< void(std::ifstream &file)> &how2ReadFile, bool ignore_error=false)"
.br
.RI "从指定文件中读取二进制内容 "
.ti -1c
.RI "static std::vector< uint8_t > \fBreadBinaryFile\fP (const std::string &path, bool ignore_error=false, bool *ok=nullptr)"
.br
.RI "从指定文件中读取二进制内容 "
.ti -1c
.RI "static std::string \fBgetAbsolutePath\fP (const std::string &path)"
.br
.RI "获取绝对路径 "
.ti -1c
.RI "static std::string \fBgetShortFileName\fP (const std::string &path, bool cut_file_extension=false)"
.br
.RI "获取文件名 "
.ti -1c
.RI "static std::vector< std::string > \fBlistFilePaths\fP (const std::string &path, \fBFilter\fP filter=\fBAll\fP, const std::vector< std::string > &file_ext_list={}, bool ignore_error=false)"
.br
.RI "获取指定路径下的所有文件或目录 "
.ti -1c
.RI "static std::vector< std::string > \fBlistFilesRecursively\fP (const std::string &path, const std::vector< std::string > &file_ext_list={}, bool ignore_error=false)"
.br
.ti -1c
.RI "static std::vector< std::string > \fBlistFiles\fP (const std::string &path, \fBFilter\fP filter=\fBAll\fP, const std::vector< std::string > &file_ext_list={}, bool ignore_error=false)"
.br
.RI "获取指定路径下的所有文件或目录 "
.in -1c
.SH "Detailed Description"
.PP 
文件系统 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBS3GF::FileSystem::Filter\fP"

.PP
文件类型筛选 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAll \fP
.TP
\f(BIFilesOnly \fP
.TP
\f(BIDirectoriesOnly \fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::FileSystem::FileSystem ()\fR [delete]\fP"

.SS "S3GF::FileSystem::FileSystem (\fBFileSystem\fP & )\fR [delete]\fP"

.SS "S3GF::FileSystem::~FileSystem ()\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const std::string & S3GF::FileSystem::currentPath ()\fR [static]\fP"

.PP
获取当前的目录 
.SS "std::string S3GF::FileSystem::getAbsolutePath (const std::string & path)\fR [static]\fP"

.PP
获取绝对路径 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定路径 
.RE
.PP
\fBReturns\fP
.RS 4
将返回完整的绝对路径 
.RE
.PP

.SS "std::string S3GF::FileSystem::getShortFileName (const std::string & path, bool cut_file_extension = \fRfalse\fP)\fR [static]\fP"

.PP
获取文件名 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定完整的路径 
.br
\fIcut_file_extension\fP 是否截断文件后缀名 
.RE
.PP
\fBReturns\fP
.RS 4
返回文件名 
.RE
.PP
To avoid the hidden files (e\&.g: \&.bashrc) in Linux!
.SS "bool S3GF::FileSystem::isDir (const std::string & path)\fR [static]\fP"

.PP
指定一个目录是否存在？ 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定目录 
.RE
.PP
\fBNote\fP
.RS 4
若指定相对目录，则会从主目录下遍历！ 
.RE
.PP

.SS "bool S3GF::FileSystem::isFile (const std::string & path)\fR [static]\fP"

.PP
指定文件是否存在 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定文件路径 
.RE
.PP
\fBNote\fP
.RS 4
若指定相对目录，则会从主目录下遍历！ 
.RE
.PP

.SS "std::vector< std::string > S3GF::FileSystem::listFilePaths (const std::string & path, \fBFilter\fP filter = \fR\fBAll\fP\fP, const std::vector< std::string > & file_ext_list = \fR{}\fP, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
获取指定路径下的所有文件或目录 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定路径 
.br
\fIfilter\fP 指定筛选类型 
.br
\fIfile_extension_filter\fP 筛选文件后缀名列表 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP
\fBReturns\fP
.RS 4
返回一个文件路径列表 
.RE
.PP
\fBSee also\fP
.RS 4
\fBlistFiles\fP 
.RE
.PP

.SS "std::vector< std::string > S3GF::FileSystem::listFiles (const std::string & path, \fBFileSystem::Filter\fP filter = \fR\fBAll\fP\fP, const std::vector< std::string > & file_ext_list = \fR{}\fP, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
获取指定路径下的所有文件或目录 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定路径 
.br
\fIfilter\fP 指定筛选类型 
.br
\fIfile_extension_filter\fP 筛选文件后缀名列表 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP
\fBReturns\fP
.RS 4
返回一个文件名列表 
.RE
.PP
\fBSee also\fP
.RS 4
\fBlistFilePaths\fP 
.RE
.PP

.SS "std::vector< std::string > S3GF::FileSystem::listFilesRecursively (const std::string & path, const std::vector< std::string > & file_ext_list = \fR{}\fP, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.SS "bool S3GF::FileSystem::mkDir (const std::string & path, bool ignore_error = \fRfalse\fP, bool recursive_create = \fRfalse\fP)\fR [static]\fP"

.PP
创建一个空目录 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定新的空目录 
.br
\fIignore_error\fP 忽略目录存在的错误 
.br
\fIrecursive_create\fP 是否递归创建目录 
.RE
.PP
\fBReturns\fP
.RS 4
返回是否成功创建一个空目录 
.RE
.PP

.SS "bool S3GF::FileSystem::mkFile (const std::string & path, bool auto_create_directory = \fRfalse\fP, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
创建一个空白文件 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定文件路径 
.br
\fIauto_create_directory\fP 是否自动创建目录（当目录不存在时递归创建） 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP

.SS "\fBFileSystem\fP & S3GF::FileSystem::operator= (const \fBFileSystem\fP & )\fR [delete]\fP"

.SS "std::vector< uint8_t > S3GF::FileSystem::readBinaryFile (const std::string & path, bool ignore_error = \fRfalse\fP, bool * ok = \fRnullptr\fP)\fR [static]\fP"

.PP
从指定文件中读取二进制内容 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定文件路径 
.br
\fIignore_error\fP 忽略存在的错误 
.br
\fIok\fP 执行是否存在问题 
.RE
.PP
\fBReturns\fP
.RS 4
返回完整的二进制内容 
.RE
.PP

.SS "bool S3GF::FileSystem::readBinaryFile (const std::string & path, const std::function< void(std::ifstream &file)> & how2ReadFile, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
从指定文件中读取二进制内容 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定文件路径 
.br
\fIhow2ReadFile\fP 指定读取文件的方法 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP
\fBReturns\fP
.RS 4
返回是否成功读取二进制内容 
.RE
.PP

.SS "std::string S3GF::FileSystem::readFile (const std::string & path, bool ignore_error = \fRfalse\fP, bool * ok = \fRnullptr\fP)\fR [static]\fP"

.PP
从指定文件中读取内容 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定文件路径 
.br
\fIignore_error\fP 忽略存在的错误 
.br
\fIok\fP 用于检查当前是否存在错误 
.RE
.PP
\fBReturns\fP
.RS 4
返回读取到的文件的所有内容 
.RE
.PP

.SS "bool S3GF::FileSystem::rmDir (const std::string & path, bool ignore_error = \fRfalse\fP, bool recursive_remove = \fRfalse\fP)\fR [static]\fP"

.PP
删除指定的目录 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定目录 
.br
\fIignore_error\fP 忽略目录存在的错误 
.br
\fIrecursive_remove\fP 递归删除此目录下的所有文件及目录 
.RE
.PP
\fBWarning\fP
.RS 4
请不要随意使用 recursive_remove 参数，如指定目录下包含重要文件，使用此参数后将一同删除！ 
.RE
.PP

.SS "bool S3GF::FileSystem::rmFile (const std::string & path, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
删除指定的文件 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定文件路径 
.br
\fIignore_error\fP 忽略文件存在的错误 
.RE
.PP

.SS "bool S3GF::FileSystem::setCurrentPath (const std::string & main_directory)\fR [static]\fP"

.PP
设置当前的目录 
.PP
\fBParameters\fP
.RS 4
\fImain_directory\fP 设定目录 
.RE
.PP

.SS "bool S3GF::FileSystem::writeBinaryFile (const std::string & path, bool append_mode, const std::function< void(std::ofstream &file)> & how2WriteFile, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
写入二进制内容到指定文件 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 指定输出文件路径 
.br
\fIappend_mode\fP 是否使用追加写入模式 
.br
\fIhow2WriteFile\fP 指定写入文件的方法 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP
\fBReturns\fP
.RS 4
返回是否成功写入文件 
.RE
.PP

.SS "bool S3GF::FileSystem::writeBinaryFile (const std::vector< uint8_t > & binaries, const std::string & path, bool append_mode, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
写入二进制内容到指定文件中 
.PP
\fBParameters\fP
.RS 4
\fIbinaries\fP 指定存储的二进制内容 
.br
\fIpath\fP 指定文件输出路径 
.br
\fIappend_mode\fP 指定是否使用追加写入模式 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP
\fBReturns\fP
.RS 4
返回是否成功写入文件 
.RE
.PP

.SS "bool S3GF::FileSystem::writeFile (const std::string & context, const std::string & path, bool append_mode, bool ignore_error = \fRfalse\fP)\fR [static]\fP"

.PP
写入内容到指定文件 
.PP
\fBParameters\fP
.RS 4
\fIcontext\fP 指定写入内容 
.br
\fIpath\fP 指定文件路径 
.br
\fIappend_mode\fP 是否使用追加写入 
.br
\fIignore_error\fP 忽略存在的错误 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
