.TH "S3GF::ClickArea" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::ClickArea
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Control\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClickArea\fP (uint64_t window_id, \fBGT\fP graphic)"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool \fBenabled\fP)"
.br
.ti -1c
.RI "bool \fBenabled\fP ()"
.br
.ti -1c
.RI "void \fBsetPressedEvent\fP (std::function< void()> function)"
.br
.ti -1c
.RI "void \fBresetPress\fP ()"
.br
.ti -1c
.RI "void \fBsetHover\fP (bool \fBenabled\fP)"
.br
.ti -1c
.RI "void \fBsetGraphic\fP (\fBGT\fP graphic)"
.br
.ti -1c
.RI "bool \fBsetPoint\fP (const \fBVector2\fP &position, uint16_t size)"
.br
.ti -1c
.RI "bool \fBsetRect\fP (const \fBGeometryF\fP &geometry)"
.br
.ti -1c
.RI "\fBGraphics::Point\fP & \fBpoint\fP ()"
.br
.ti -1c
.RI "\fBGraphics::Rectangle\fP & \fBrectangle\fP ()"
.br
.ti -1c
.RI "bool \fBgetPoint\fP (\fBGraphics::Point\fP &\fBpoint\fP)"
.br
.ti -1c
.RI "bool \fBgetRect\fP (\fBGraphics::Rectangle\fP &rect)"
.br
.ti -1c
.RI "bool \fBisPressed\fP () const"
.br
.ti -1c
.RI "bool \fBisHovered\fP () const"
.br
.ti -1c
.RI "bool \fBisEntered\fP () const"
.br
.ti -1c
.RI "bool \fBisDown\fP () const"
.br
.ti -1c
.RI "bool \fBisLeft\fP () const"
.br
.ti -1c
.RI "size_t \fBindex\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::ClickArea::ClickArea (uint64_t window_id, \fBGT\fP graphic)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool S3GF::ClickArea::enabled ()"

.SS "bool S3GF::ClickArea::getPoint (\fBGraphics::Point\fP & point)"

.SS "bool S3GF::ClickArea::getRect (\fBGraphics::Rectangle\fP & rect)"

.SS "size_t S3GF::ClickArea::index () const\fR [nodiscard]\fP"

.SS "bool S3GF::ClickArea::isDown () const\fR [nodiscard]\fP"

.SS "bool S3GF::ClickArea::isEntered () const\fR [nodiscard]\fP"

.SS "bool S3GF::ClickArea::isHovered () const\fR [nodiscard]\fP"

.SS "bool S3GF::ClickArea::isLeft () const\fR [nodiscard]\fP"

.SS "bool S3GF::ClickArea::isPressed () const\fR [nodiscard]\fP"

.SS "\fBGraphics::Point\fP & S3GF::ClickArea::point ()"

.SS "\fBGraphics::Rectangle\fP & S3GF::ClickArea::rectangle ()"

.SS "void S3GF::ClickArea::resetPress ()"

.SS "void S3GF::ClickArea::setEnabled (bool enabled)"

.SS "void S3GF::ClickArea::setGraphic (\fBGT\fP graphic)"

.SS "void S3GF::ClickArea::setHover (bool enabled)"

.SS "bool S3GF::ClickArea::setPoint (const \fBVector2\fP & position, uint16_t size)"

.SS "void S3GF::ClickArea::setPressedEvent (std::function< void()> function)"

.SS "bool S3GF::ClickArea::setRect (const \fBGeometryF\fP & geometry)"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
