.TH "S3GF::EventSystem" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::EventSystem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventSystem\fP (\fBEventSystem\fP &&)=delete"
.br
.ti -1c
.RI "\fBEventSystem\fP (const \fBEventSystem\fP &)=delete"
.br
.ti -1c
.RI "\fBEventSystem\fP & \fBoperator=\fP (\fBEventSystem\fP &&)=delete"
.br
.ti -1c
.RI "\fBEventSystem\fP & \fBoperator=\fP (const \fBEventSystem\fP &)=delete"
.br
.ti -1c
.RI "\fB~EventSystem\fP ()"
.br
.ti -1c
.RI "void \fBappendEvent\fP (uint64_t id, const std::function< void(SDL_Event)> &event)"
.br
.ti -1c
.RI "void \fBremoveEvent\fP (uint64_t id)"
.br
.ti -1c
.RI "void \fBclearEvent\fP ()"
.br
.ti -1c
.RI "size_t \fBeventCount\fP () const"
.br
.ti -1c
.RI "bool \fBrun\fP ()"
.br
.ti -1c
.RI "bool \fBisKeyDown\fP () const"
.br
.ti -1c
.RI "bool \fBisMouseButtonDown\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEventSystem\fP * \fBglobal\fP (\fBEngine\fP *engine)"
.br
.ti -1c
.RI "static \fBEventSystem\fP * \fBglobal\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "S3GF::EventSystem::EventSystem (\fBEventSystem\fP && )\fR [delete]\fP"

.SS "S3GF::EventSystem::EventSystem (const \fBEventSystem\fP & )\fR [delete]\fP"

.SS "S3GF::EventSystem::~EventSystem ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void S3GF::EventSystem::appendEvent (uint64_t id, const std::function< void(SDL_Event)> & event)"

.SS "void S3GF::EventSystem::clearEvent ()"

.SS "size_t S3GF::EventSystem::eventCount () const"

.SS "\fBEventSystem\fP * S3GF::EventSystem::global ()\fR [static]\fP"

.SS "\fBEventSystem\fP * S3GF::EventSystem::global (\fBEngine\fP * engine)\fR [static]\fP"

.SS "bool S3GF::EventSystem::isKeyDown () const\fR [nodiscard]\fP"

.SS "bool S3GF::EventSystem::isMouseButtonDown () const\fR [nodiscard]\fP"

.SS "\fBEventSystem\fP & S3GF::EventSystem::operator= (const \fBEventSystem\fP & )\fR [delete]\fP"

.SS "\fBEventSystem\fP & S3GF::EventSystem::operator= (\fBEventSystem\fP && )\fR [delete]\fP"

.SS "void S3GF::EventSystem::removeEvent (uint64_t id)"

.SS "bool S3GF::EventSystem::run ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
