.TH "S3GF::DateTime::DT" 3 "Thu Nov 27 2025 19:54:34" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::DateTime::DT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DateTime\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fByear\fP"
.br
.ti -1c
.RI "uint8_t \fBmonth\fP"
.br
.ti -1c
.RI "uint8_t \fBday\fP"
.br
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.ti -1c
.RI "uint8_t \fBminute\fP"
.br
.ti -1c
.RI "uint8_t \fBsecond\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t S3GF::DateTime::DT::day"

.SS "uint8_t S3GF::DateTime::DT::hour"

.SS "uint8_t S3GF::DateTime::DT::minute"

.SS "uint8_t S3GF::DateTime::DT::month"

.SS "uint8_t S3GF::DateTime::DT::second"

.SS "uint16_t S3GF::DateTime::DT::year"


.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
