.TH "D:/Coding/S3GF/src/Basic.h" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Basic.h \- 基本模块  

.SH SYNOPSIS
.br
.PP
\fR#include 'Libs\&.h'\fP
.br
\fR#include 'Algorithm/Draw\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "struct \fBS3GF::Geometry\fP"
.br
.RI "Including position and size\&. "
.ti -1c
.RI "struct \fBS3GF::Vector2\fP"
.br
.RI "向量坐标 "
.ti -1c
.RI "struct \fBS3GF::Size\fP"
.br
.RI "尺寸、大小 "
.ti -1c
.RI "struct \fBS3GF::GeometryF\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "struct \fBS3GF::Matrix2D< T >\fP"
.br
.RI "二维矩阵 "
.ti -1c
.RI "struct \fBS3GF::Matrix2D< T >::Position\fP"
.br
.ti -1c
.RI "class \fBS3GF::Graphics::Point\fP"
.br
.ti -1c
.RI "class \fBS3GF::Graphics::Line\fP"
.br
.ti -1c
.RI "class \fBS3GF::Graphics::Rectangle\fP"
.br
.ti -1c
.RI "class \fBS3GF::Graphics::Triangle\fP"
.br
.ti -1c
.RI "class \fBS3GF::Graphics::Ellipse\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace "
.ti -1c
.RI "namespace \fBStdColor\fP"
.br
.RI "Predefined Standard Color (40 colors) "
.ti -1c
.RI "namespace \fBS3GF::StdColor\fP"
.br
.ti -1c
.RI "namespace \fBRGBAColor\fP"
.br
.RI "Predefined colors, named in RGBA format "
.ti -1c
.RI "namespace \fBS3GF::RGBAColor\fP"
.br
.ti -1c
.RI "namespace \fBGraphics\fP"
.br
.RI "基本图形 "
.ti -1c
.RI "namespace \fBS3GF::Graphics\fP"
.br
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBBASIC_H\fP"
.br
.ti -1c
.RI "#define \fBSLEEP\fP(sec)"
.br
.ti -1c
.RI "#define \fBSLEEP_MS\fP(millisec)"
.br
.ti -1c
.RI "#define \fBSLEEP_NS\fP(nanosec)"
.br
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "using \fBSRenderer\fP = SDL_Renderer"
.br
.ti -1c
.RI "using \fBSSurface\fP = SDL_Surface"
.br
.ti -1c
.RI "using \fBSTexture\fP = SDL_Texture"
.br
.ti -1c
.RI "using \fBSEvent\fP = SDL_Event"
.br
.ti -1c
.RI "using \fBSWinEvent\fP = SDL_WindowEvent"
.br
.ti -1c
.RI "using \fBSWindow\fP = SDL_Window"
.br
.ti -1c
.RI "using \fBSWindowID\fP = SDL_WindowID"
.br
.ti -1c
.RI "using \fBSColor\fP = SDL_Color"
.br
.ti -1c
.RI "using \fBSCursor\fP = SDL_Cursor"
.br
.ti -1c
.RI "using \fBSStdCursor\fP = SDL_SystemCursor"
.br
.ti -1c
.RI "using \fBSAudioSpec\fP = SDL_AudioSpec"
.br
.ti -1c
.RI "using \fBStringList\fP = std::vector<std::string>"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBGeometry\fP \fBS3GF::toGeometryInt\fP (const \fBGeometryF\fP &geo)"
.br
.ti -1c
.RI "\fBGeometryF\fP \fBS3GF::toGeometryFloat\fP (const \fBGeometry\fP &geo)"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Black\fP = {0, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::White\fP = {255, 255, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Red\fP = {255, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Green\fP = {0, 255, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Blue\fP = {0, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Yellow\fP = {255, 255, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Cyan\fP = {0, 255, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Magenta\fP = {255, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::DarkRed\fP = {128, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::FireRed\fP = {200, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::BrightRed\fP = {255, 50, 50, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Coral\fP = {255, 127, 80, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Salmon\fP = {250, 128, 114, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::LightPink\fP = {255, 174, 185, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::DarkGreen\fP = {0, 128, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::ForestGreen\fP = {34, 139, 34, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::LimeGreen\fP = {50, 205, 50, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Mint\fP = {189, 252, 201, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::LightGreen\fP = {144, 238, 144, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Olive\fP = {128, 128, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::DarkBlue\fP = {0, 0, 128, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Navy\fP = {0, 32, 64, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::SkyBlue\fP = {135, 206, 235, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::LightBlue\fP = {173, 216, 230, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::RoyalBlue\fP = {65, 105, 225, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Indigo\fP = {75, 0, 130, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Gold\fP = {255, 215, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Orange\fP = {255, 165, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::DarkOrange\fP = {255, 140, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Peach\fP = {255, 218, 185, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Amber\fP = {255, 193, 37, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Khaki\fP = {240, 230, 140, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Purple\fP = {128, 0, 128, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::DarkPurple\fP = {72, 61, 139, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Violet\fP = {148, 0, 211, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Fuchsia\fP = {255, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Pink\fP = {255, 192, 203, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Lavender\fP = {230, 230, 250, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::Gray\fP = {128, 128, 128, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::LightGray\fP = {200, 200, 200, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::StdColor::DarkGray\fP = {64, 64, 64, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::Transparent\fP = {255, 255, 255, 0}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::HalfTransparent\fP = {255, 255, 255, 128}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::Black\fP = {0, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::White\fP = {255, 255, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedPure\fP = {255, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedDark\fP = {153, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedDarker\fP = {102, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedWine\fP = {85, 0, 34, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedRose\fP = {255, 26, 99, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedPink\fP = {255, 105, 180, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedLightPink\fP = {255, 179, 217, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedPalePink\fP = {255, 218, 232, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedCoral\fP = {255, 114, 86, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedOrange\fP = {255, 69, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedBrick\fP = {178, 34, 34, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedRust\fP = {183, 65, 14, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedScarlet\fP = {255, 36, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedMagenta\fP = {255, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedFuchsia\fP = {219, 112, 219, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedRosePink\fP = {255, 52, 179, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedDeepPink\fP = {255, 20, 147, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedPeachPink\fP = {255, 153, 170, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedCherryBlossom\fP = {255, 228, 225, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedRouge\fP = {210, 0, 82, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedVermilion\fP = {227, 38, 54, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedBegonia\fP = {255, 99, 71, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedPomegranate\fP = {204, 0, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedLightTrans\fP = {255, 192, 192, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedPaleTrans\fP = {255, 224, 224, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedDarkTrans\fP = {153, 50, 50, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedRoseTrans\fP = {255, 105, 180, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedMagentaTrans\fP = {255, 153, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedCoralTrans\fP = {255, 160, 122, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedOrangeTrans\fP = {255, 127, 80, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedFuchsiaTrans\fP = {230, 145, 230, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::RedBrickTrans\fP = {199, 21, 133, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenPure\fP = {0, 255, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenDark\fP = {0, 153, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenInk\fP = {0, 102, 51, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenOlive\fP = {107, 142, 35, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenGrass\fP = {34, 139, 34, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenLight\fP = {144, 238, 144, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenPale\fP = {152, 251, 152, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenMint\fP = {189, 252, 201, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenEmerald\fP = {0, 201, 87, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenJade\fP = {50, 205, 50, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenPine\fP = {2, 94, 47, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenWillow\fP = {134, 204, 204, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenBean\fP = {194, 231, 181, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenMoss\fP = {115, 147, 115, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenBamboo\fP = {0, 168, 107, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenLime\fP = {50, 205, 50, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenApple\fP = {145, 238, 145, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenForest\fP = {34, 139, 34, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenIvy\fP = {7, 101, 68, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenPeacock\fP = {0, 166, 166, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenCyan\fP = {0, 255, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenTurquoise\fP = {64, 224, 208, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenMintCyan\fP = {102, 255, 204, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenLightTrans\fP = {173, 255, 173, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenPaleTrans\fP = {204, 255, 204, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenDarkTrans\fP = {50, 153, 50, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenOliveTrans\fP = {138, 154, 70, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenJadeTrans\fP = {102, 255, 102, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenLimeTrans\fP = {127, 255, 0, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenCyanTrans\fP = {102, 255, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenTurquoiseTrans\fP = {128, 240, 224, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenMossTrans\fP = {143, 188, 143, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::GreenBambooTrans\fP = {51, 204, 153, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BluePure\fP = {0, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueDark\fP = {0, 0, 153, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueNavy\fP = {0, 32, 96, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSapphire\fP = {0, 102, 204, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSky\fP = {135, 206, 235, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueLight\fP = {173, 216, 230, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BluePale\fP = {204, 232, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueBaby\fP = {176, 224, 230, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSea\fP = {28, 134, 238, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueLake\fP = {0, 191, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueCobalt\fP = {65, 105, 225, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueIndigo\fP = {75, 0, 130, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueViolet\fP = {138, 43, 226, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueLavender\fP = {191, 211, 254, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueStone\fP = {100, 149, 237, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueIce\fP = {240, 248, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSteel\fP = {70, 130, 180, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BluePrussian\fP = {29, 53, 87, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueRoyal\fP = {0, 64, 128, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BluePeacock\fP = {30, 144, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueCyan\fP = {0, 255, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueLilac\fP = {169, 184, 208, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueDeepSky\fP = {0, 191, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueLightTrans\fP = {173, 216, 230, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BluePaleTrans\fP = {211, 235, 250, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueDarkTrans\fP = {65, 105, 225, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueNavyTrans\fP = {30, 144, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSapphireTrans\fP = {0, 128, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueIndigoTrans\fP = {106, 90, 205, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueVioletTrans\fP = {153, 102, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSeaTrans\fP = {64, 170, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::BlueSteelTrans\fP = {100, 149, 237, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixYellow\fP = {255, 255, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixYellowDark\fP = {204, 204, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixYellowLemon\fP = {255, 246, 143, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixOrangeYellow\fP = {255, 165, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixAmber\fP = {255, 193, 37, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixGold\fP = {255, 215, 0, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixPurple\fP = {128, 0, 128, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixPurpleDark\fP = {72, 61, 139, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixPurpleLight\fP = {199, 21, 133, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixPurplePale\fP = {216, 191, 216, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixViolet\fP = {143, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixFuchsia\fP = {255, 0, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixCyan\fP = {0, 255, 255, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixCyanDark\fP = {0, 139, 139, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixCyanLight\fP = {175, 238, 238, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixGray\fP = {128, 128, 128, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixGrayDark\fP = {64, 64, 64, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixGrayLight\fP = {192, 192, 192, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixSilver\fP = {192, 192, 192, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixBrown\fP = {165, 42, 42, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixBrownDark\fP = {101, 67, 33, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixBrownLight\fP = {210, 180, 140, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixKhaki\fP = {240, 230, 140, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixBeige\fP = {245, 245, 220, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixCream\fP = {255, 253, 208, 255}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixYellowTrans\fP = {255, 255, 153, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixPurpleTrans\fP = {204, 153, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixCyanTrans\fP = {153, 255, 255, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixGrayTrans\fP = {192, 192, 192, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixBrownTrans\fP = {205, 133, 63, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixKhakiTrans\fP = {245, 245, 205, 192}"
.br
.ti -1c
.RI "constexpr \fBSColor\fP \fBS3GF::RGBAColor::MixAmberTrans\fP = {255, 215, 105, 192}"
.br
.in -1c
.SH "详细描述"
.PP 
基本模块 

定义引擎基础数据结构和图形实体，是整个引擎的基础数据层。

.PP
\fB版权所有\fP
.RS 4
Copyright © 2025 CatIsNotFound 
.RE
.PP
\fB作者\fP
.RS 4
CatIsNotFound 
.RE
.PP

.SH "宏定义说明"
.PP 
.SS "#define BASIC_H"

.SS "#define SLEEP( sec)"
\fB值:\fP
.nf
std::this_thread::sleep_for(std::chrono::seconds(sec))
.PP
.fi

.SS "#define SLEEP_MS( millisec)"
\fB值:\fP
.nf
std::this_thread::sleep_for(std::chrono::milliseconds(millisec))
.PP
.fi

.SS "#define SLEEP_NS( nanosec)"
\fB值:\fP
.nf
std::this_thread::sleep_for(std::chrono::nanoseconds(nanosec))
.PP
.fi

.SH "类型定义说明"
.PP 
.SS "using \fBSAudioSpec\fP = SDL_AudioSpec"

.SS "using \fBSColor\fP = SDL_Color"

.SS "using \fBSCursor\fP = SDL_Cursor"

.SS "using \fBSEvent\fP = SDL_Event"

.SS "using \fBSRenderer\fP = SDL_Renderer"

.SS "using \fBSStdCursor\fP = SDL_SystemCursor"

.SS "using \fBSSurface\fP = SDL_Surface"

.SS "using \fBSTexture\fP = SDL_Texture"

.SS "using \fBStringList\fP = std::vector<std::string>"

.SS "using \fBSWindow\fP = SDL_Window"

.SS "using \fBSWindowID\fP = SDL_WindowID"

.SS "using \fBSWinEvent\fP = SDL_WindowEvent"

.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
