.TH "D:/Coding/S3GF/src/Algorithm/Collider.h" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Algorithm/Collider.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Basic\&.h'\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace "
.ti -1c
.RI "namespace \fBS3GF::Algorithm\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "int8_t \fBS3GF::Algorithm::comparePosInRect\fP (const \fBVector2\fP &vec, const \fBGraphics::Rectangle\fP &rect)"
.br
.ti -1c
.RI "int8_t \fBS3GF::Algorithm::comparePosInPoint\fP (const \fBVector2\fP &pos, const \fBGraphics::Point\fP &point)"
.br
.ti -1c
.RI "int8_t \fBS3GF::Algorithm::comparePoints\fP (const \fBGraphics::Point\fP &point1, const \fBGraphics::Point\fP &point2)"
.br
.ti -1c
.RI "int8_t \fBS3GF::Algorithm::compareRects\fP (const \fBGraphics::Rectangle\fP &rect1, const \fBGraphics::Rectangle\fP &rect2)"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
