.TH "D:/Coding/S3GF/src/Controls/Control.cpp" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Controls/Control.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Control\&.h'\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace "
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
