.TH "D:/Coding/S3GF/src/Controls/Control.h" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Controls/Control.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Core\&.h'\fP
.br
\fR#include '\&.\&./Utils/Cursor\&.h'\fP
.br
\fR#include 'Algorithm/Collider\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBS3GF::ClickArea\fP"
.br
.ti -1c
.RI "struct \fBS3GF::ColorStatus\fP"
.br
.ti -1c
.RI "class \fBS3GF::AbstractControl\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace "
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "using \fBS3GF::GT\fP = std::variant<std::monostate, \fBGraphics::Point\fP, \fBGraphics::Rectangle\fP>"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "uint64_t \fBS3GF::_next_id\fP = 0"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
