.TH "D:/Coding/S3GF/src/Algorithm/Draw.h" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/Algorithm/Draw.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Libs\&.h'\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP Namespace "
.ti -1c
.RI "namespace \fBS3GF::Algorithm\fP"
.br
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBS3GF_DRAW_H\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "SDL_FColor \fBS3GF::Algorithm::convert2FColor\fP (const SDL_Color &color)"
.br
.ti -1c
.RI "SDL_Color \fBS3GF::Algorithm::convert2Color\fP (const SDL_FColor &color)"
.br
.ti -1c
.RI "void \fBS3GF::Algorithm::calcPoint\fP (const \fBVector2\fP &position, float radius, SDL_Color color, std::vector< SDL_Vertex > &vertices, std::vector< int > &indices, const uint16_t count=32)"
.br
.ti -1c
.RI "void \fBS3GF::Algorithm::calcLine\fP (float x1, float y1, float x2, float y2, uint16_t thickness, const SDL_Color &color, std::array< SDL_Vertex, 4 > &vertex, std::array< int, 6 > &indices)"
.br
.ti -1c
.RI "void \fBS3GF::Algorithm::calcRectangleBorder\fP (const \fBGeometryF\fP &geometry, uint16_t border_size, std::array< SDL_FRect, 4 > &borders)"
.br
.ti -1c
.RI "void \fBS3GF::Algorithm::calcTriangle\fP (const \fBVector2\fP &pos1, const \fBVector2\fP &pos2, const \fBVector2\fP &pos3, const SDL_Color &color, std::array< SDL_Vertex, 3 > &vertices, std::array< int, 3 > &indices)"
.br
.ti -1c
.RI "void \fBS3GF::Algorithm::calcEllipse\fP (const \fBVector2\fP &center_pt, const \fBSize\fP &radius, const SDL_Color &color, float degree, uint16_t segment, std::vector< SDL_Vertex > &vertices, std::vector< int > &indices)"
.br
.ti -1c
.RI "void \fBS3GF::Algorithm::calcEllipseRing\fP (const \fBVector2\fP &center_pt, const \fBSize\fP &radius, uint16_t border_size, const SDL_Color &border_color, float degree, uint16_t segment, std::vector< SDL_Vertex > &vertices, std::vector< int > &indices)"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define S3GF_DRAW_H"

.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
