.TH "RGBAColor" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBAColor \- Predefined colors, named in RGBA format  

.SH SYNOPSIS
.br
.PP
.SH "详细描述"
.PP 
Predefined colors, named in RGBA format 


.PP
\fB参见\fP
.RS 4
\fBBasic\&.h\fP 
.RE
.PP

.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
