.TH "S3GF::Graphics" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Graphics
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBEllipse\fP"
.br
.ti -1c
.RI "class \fBLine\fP"
.br
.ti -1c
.RI "class \fBPoint\fP"
.br
.ti -1c
.RI "class \fBRectangle\fP"
.br
.ti -1c
.RI "class \fBTriangle\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
