.TH "S3GF::Texture" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Texture
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Components\&.h>\fP
.PP
被 \fBS3GF::TextureAtlas\fP 继承\&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBTexture\fP (const \fBTexture\fP &)=delete"
.br
.ti -1c
.RI "\fBTexture\fP (\fBTexture\fP &&)=delete"
.br
.ti -1c
.RI "\fBTexture\fP & \fBoperator=\fP (const \fBTexture\fP &)=delete"
.br
.ti -1c
.RI "\fBTexture\fP & \fBoperator=\fP (\fBTexture\fP &&)=delete"
.br
.ti -1c
.RI "\fBTexture\fP (const std::string &path, \fBRenderer\fP *renderer)"
.br
.ti -1c
.RI "\fBTexture\fP (SDL_Surface *surface, \fBRenderer\fP *renderer, bool deep_copy=false)"
.br
.ti -1c
.RI "\fBTexture\fP (\fBRenderer\fP *renderer, SDL_PixelFormat format, int width, int height, SDL_TextureAccess access)"
.br
.ti -1c
.RI "\fB~Texture\fP ()"
.br
.ti -1c
.RI "\fBRenderer\fP * \fBrender\fP () const"
.br
.ti -1c
.RI "bool \fBsetImagePath\fP (const std::string &path)"
.br
.ti -1c
.RI "const std::string & \fBimagePath\fP () const"
.br
.ti -1c
.RI "bool \fBsetImageFromSurface\fP (SDL_Surface *surface, bool deep_copy=false)"
.br
.ti -1c
.RI "SDL_Texture * \fBself\fP () const"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "\fBProperty\fP * \fBproperty\fP ()"
.br
.ti -1c
.RI "virtual void \fBdraw\fP () const"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Texture::Texture (const \fBTexture\fP & )\fR [delete]\fP"

.SS "S3GF::Texture::Texture (\fBTexture\fP && )\fR [delete]\fP"

.SS "S3GF::Texture::Texture (const std::string & path, \fBRenderer\fP * renderer)\fR [explicit]\fP"

.SS "S3GF::Texture::Texture (SDL_Surface * surface, \fBRenderer\fP * renderer, bool deep_copy = \fRfalse\fP)\fR [explicit]\fP"

.SS "S3GF::Texture::Texture (\fBRenderer\fP * renderer, SDL_PixelFormat format, int width, int height, SDL_TextureAccess access)\fR [explicit]\fP"

.SS "S3GF::Texture::~Texture ()"

.SH "成员函数说明"
.PP 
.SS "void S3GF::Texture::draw () const\fR [virtual]\fP"

.PP
被 \fBS3GF::TextureAtlas\fP 重载\&.
.SS "const std::string & S3GF::Texture::imagePath () const\fR [nodiscard]\fP"

.SS "bool S3GF::Texture::isValid () const\fR [nodiscard]\fP"

.SS "\fBTexture\fP & S3GF::Texture::operator= (const \fBTexture\fP & )\fR [delete]\fP"

.SS "\fBTexture\fP & S3GF::Texture::operator= (\fBTexture\fP && )\fR [delete]\fP"

.SS "\fBProperty\fP * S3GF::Texture::property ()"

.SS "\fBRenderer\fP * S3GF::Texture::render () const"

.SS "SDL_Texture * S3GF::Texture::self () const\fR [nodiscard]\fP"

.SS "bool S3GF::Texture::setImageFromSurface (SDL_Surface * surface, bool deep_copy = \fRfalse\fP)"

.SS "bool S3GF::Texture::setImagePath (const std::string & path)"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
