.TH "S3GF::FontDatabase" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::FontDatabase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "类"

.in +1c
.ti -1c
.RI "struct \fBFontInfo\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBFontDatabase\fP ()=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP (const \fBFontDatabase\fP &)=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP (\fBFontDatabase\fP &&)=delete"
.br
.ti -1c
.RI "\fB~FontDatabase\fP ()=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP & \fBoperator=\fP (const \fBFontDatabase\fP &)=delete"
.br
.ti -1c
.RI "\fBFontDatabase\fP & \fBoperator=\fP (\fBFontDatabase\fP &&)=delete"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static \fBFontMap\fP \fBgetFontDatabaseFromSystem\fP ()"
.br
.ti -1c
.RI "static std::string \fBfindFontFromSystem\fP (const std::string &font_name)"
.br
.ti -1c
.RI "static std::vector< \fBFontInfo\fP > \fBgetSystemDefaultFont\fP ()"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::FontDatabase::FontDatabase ()\fR [delete]\fP"

.SS "S3GF::FontDatabase::FontDatabase (const \fBFontDatabase\fP & )\fR [delete]\fP"

.SS "S3GF::FontDatabase::FontDatabase (\fBFontDatabase\fP && )\fR [delete]\fP"

.SS "S3GF::FontDatabase::~FontDatabase ()\fR [delete]\fP"

.SH "成员函数说明"
.PP 
.SS "std::string S3GF::FontDatabase::findFontFromSystem (const std::string & font_name)\fR [static]\fP"

.SS "\fBFontMap\fP S3GF::FontDatabase::getFontDatabaseFromSystem ()\fR [static]\fP"

.SS "std::vector< \fBFontDatabase::FontInfo\fP > S3GF::FontDatabase::getSystemDefaultFont ()\fR [static]\fP"

.SS "\fBFontDatabase\fP & S3GF::FontDatabase::operator= (const \fBFontDatabase\fP & )\fR [delete]\fP"

.SS "\fBFontDatabase\fP & S3GF::FontDatabase::operator= (\fBFontDatabase\fP && )\fR [delete]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
