.TH "S3GF::DateTime::DT" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::DateTime::DT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DateTime\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "uint16_t \fByear\fP"
.br
.ti -1c
.RI "uint8_t \fBmonth\fP"
.br
.ti -1c
.RI "uint8_t \fBday\fP"
.br
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.ti -1c
.RI "uint8_t \fBminute\fP"
.br
.ti -1c
.RI "uint8_t \fBsecond\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "uint8_t S3GF::DateTime::DT::day"

.SS "uint8_t S3GF::DateTime::DT::hour"

.SS "uint8_t S3GF::DateTime::DT::minute"

.SS "uint8_t S3GF::DateTime::DT::month"

.SS "uint8_t S3GF::DateTime::DT::second"

.SS "uint16_t S3GF::DateTime::DT::year"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
