.TH "S3GF::Matrix2D< T >::Position" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Matrix2D< T >::Position
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBPosition\fP ()"
.br
.ti -1c
.RI "\fBPosition\fP (uint32_t \fBrow\fP, uint32_t \fBcol\fP)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBPosition\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBPosition\fP &p) const"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "uint32_t \fBrow\fP"
.br
.ti -1c
.RI "uint32_t \fBcol\fP"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Position::Position ()\fR [inline]\fP"

.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Position::Position (uint32_t row, uint32_t col)\fR [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::isValid () const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator!= (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator< (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator<= (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator== (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator> (const \fBPosition\fP & p) const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::Position::operator>= (const \fBPosition\fP & p) const\fR [inline]\fP"

.SH "类成员变量说明"
.PP 
.SS "template<typename T> uint32_t \fBS3GF::Matrix2D\fP< T >::Position::col"

.SS "template<typename T> uint32_t \fBS3GF::Matrix2D\fP< T >::Position::row"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
