.TH "S3GF" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF \- \fBS3GF\fP 空间  

.SH SYNOPSIS
.br
.PP
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBAlgorithm\fP"
.br
.ti -1c
.RI "namespace \fBGraphics\fP"
.br
.ti -1c
.RI "namespace \fBStdColor\fP"
.br
.in -1c
.SS "类"

.in +1c
.ti -1c
.RI "class \fBAbstractControl\fP"
.br
.ti -1c
.RI "class \fBAudioSystem\fP"
.br
.ti -1c
.RI "class \fBClickArea\fP"
.br
.ti -1c
.RI "class \fBCursor\fP"
.br
.RI "鼠标光标 "
.ti -1c
.RI "class \fBDateTime\fP"
.br
.ti -1c
.RI "class \fBEngine\fP"
.br
.ti -1c
.RI "class \fBEventSystem\fP"
.br
.ti -1c
.RI "class \fBFont\fP"
.br
.ti -1c
.RI "struct \fBGeometry\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "struct \fBGeometryF\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "struct \fBMatrix2D\fP"
.br
.RI "二维矩阵 "
.ti -1c
.RI "struct \fBProperty\fP"
.br
.ti -1c
.RI "class \fBRandomGenerator\fP"
.br
.ti -1c
.RI "class \fBRenderer\fP"
.br
.ti -1c
.RI "struct \fBSize\fP"
.br
.RI "尺寸、大小 "
.ti -1c
.RI "class \fBTaskQueue\fP"
.br
.ti -1c
.RI "class \fBTasksManager\fP"
.br
.ti -1c
.RI "class \fBTextSystem\fP"
.br
.ti -1c
.RI "class \fBTexture\fP"
.br
.ti -1c
.RI "class \fBThreadPool\fP"
.br
.ti -1c
.RI "class \fBTimer\fP"
.br
.ti -1c
.RI "class \fBTrigger\fP"
.br
.ti -1c
.RI "struct \fBVector2\fP"
.br
.RI "向量坐标 "
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "using \fBGT\fP = std::variant<std::monostate, \fBGraphics::Point\fP, \fBGraphics::Rectangle\fP>"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "uint64_t \fB_next_id\fP = 0"
.br
.in -1c
.SH "详细描述"
.PP 
\fBS3GF\fP 空间 

所有库都将被存储于此命名空间 
.SH "类型定义说明"
.PP 
.SS "using \fBS3GF::GT\fP = std::variant<std::monostate, \fBGraphics::Point\fP, \fBGraphics::Rectangle\fP>"

.SH "变量说明"
.PP 
.SS "uint64_t S3GF::_next_id = 0\fR [inline]\fP"

.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
