.TH "S3GF::TaskQueue< T >" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TaskQueue< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Queue\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBTaskQueue\fP (\fBTaskQueue\fP &&)=delete"
.br
.ti -1c
.RI "\fBTaskQueue\fP (const \fBTaskQueue\fP &)=delete"
.br
.ti -1c
.RI "\fBTaskQueue\fP & \fBoperator=\fP (\fBTaskQueue\fP &&)=delete"
.br
.ti -1c
.RI "\fBTaskQueue\fP & \fBoperator=\fP (const \fBTaskQueue\fP &)=delete"
.br
.ti -1c
.RI "\fBTaskQueue\fP ()=default"
.br
.ti -1c
.RI "\fB~TaskQueue\fP ()=default"
.br
.ti -1c
.RI "bool \fBpush\fP (const T &data)"
.br
.ti -1c
.RI "bool \fBpush\fP (T &&data)"
.br
.ti -1c
.RI "bool \fBpop\fP (T &data)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "bool \fBisRunning\fP () const"
.br
.ti -1c
.RI "void \fBsetMaxSize\fP (size_t max_size)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "const T & \fBfront\fP () const"
.br
.ti -1c
.RI "const T & \fBback\fP () const"
.br
.ti -1c
.RI "void \fBsetDeletor\fP (const std::function< void(T &)> &deletor)"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "template<typename T> \fBS3GF::TaskQueue\fP< T >::TaskQueue (\fBTaskQueue\fP< T > && )\fR [delete]\fP"

.SS "template<typename T> \fBS3GF::TaskQueue\fP< T >::TaskQueue (const \fBTaskQueue\fP< T > & )\fR [delete]\fP"

.SS "template<typename T> \fBS3GF::TaskQueue\fP< T >::TaskQueue ()\fR [explicit]\fP, \fR [default]\fP"

.SS "template<typename T> \fBS3GF::TaskQueue\fP< T >::~\fBTaskQueue\fP ()\fR [default]\fP"

.SH "成员函数说明"
.PP 
.SS "template<typename T> const T & \fBS3GF::TaskQueue\fP< T >::back () const\fR [inline]\fP"

.SS "template<typename T> void \fBS3GF::TaskQueue\fP< T >::clear ()\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::TaskQueue\fP< T >::empty () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "template<typename T> const T & \fBS3GF::TaskQueue\fP< T >::front () const\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::TaskQueue\fP< T >::isRunning () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "template<typename T> \fBTaskQueue\fP & \fBS3GF::TaskQueue\fP< T >::operator= (const \fBTaskQueue\fP< T > & )\fR [delete]\fP"

.SS "template<typename T> \fBTaskQueue\fP & \fBS3GF::TaskQueue\fP< T >::operator= (\fBTaskQueue\fP< T > && )\fR [delete]\fP"

.SS "template<typename T> bool \fBS3GF::TaskQueue\fP< T >::pop (T & data)\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::TaskQueue\fP< T >::push (const T & data)\fR [inline]\fP"

.SS "template<typename T> bool \fBS3GF::TaskQueue\fP< T >::push (T && data)\fR [inline]\fP"

.SS "template<typename T> void \fBS3GF::TaskQueue\fP< T >::setDeletor (const std::function< void(T &)> & deletor)\fR [inline]\fP"

.SS "template<typename T> void \fBS3GF::TaskQueue\fP< T >::setMaxSize (size_t max_size)\fR [inline]\fP"

.SS "template<typename T> size_t \fBS3GF::TaskQueue\fP< T >::size () const\fR [inline]\fP, \fR [nodiscard]\fP"

.SS "template<typename T> void \fBS3GF::TaskQueue\fP< T >::start ()\fR [inline]\fP"

.SS "template<typename T> void \fBS3GF::TaskQueue\fP< T >::stop ()\fR [inline]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
