.TH "S3GF::Logger" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Logger
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Logger\&.h>\fP
.SS "Public 类型"

.in +1c
.ti -1c
.RI "enum \fBLogLevel\fP { \fBDEBUG\fP, \fBINFO\fP, \fBWARN\fP, \fBERROR\fP, \fBFATAL\fP }"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBLogger\fP ()=delete"
.br
.ti -1c
.RI "\fBLogger\fP (\fBLogger\fP &&)=delete"
.br
.ti -1c
.RI "\fBLogger\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (\fBLogger\fP &&)=delete"
.br
.ti -1c
.RI "\fBLogger\fP & \fBoperator=\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "\fB~Logger\fP ()=delete"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static void \fBlog\fP (const std::string &message, \fBLogLevel\fP level=\fBDEBUG\fP)"
.br
.ti -1c
.RI "static void \fBsetBaseLogLevel\fP (\fBLogLevel\fP level)"
.br
.ti -1c
.RI "static std::string \fBlastError\fP ()"
.br
.in -1c
.SH "成员枚举类型说明"
.PP 
.SS "enum \fBS3GF::Logger::LogLevel\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\f(BIDEBUG \fP
.TP
\f(BIINFO \fP
.TP
\f(BIWARN \fP
.TP
\f(BIERROR \fP
.TP
\f(BIFATAL \fP
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Logger::Logger ()\fR [delete]\fP"

.SS "S3GF::Logger::Logger (\fBLogger\fP && )\fR [delete]\fP"

.SS "S3GF::Logger::Logger (const \fBLogger\fP & )\fR [delete]\fP"

.SS "S3GF::Logger::~Logger ()\fR [delete]\fP"

.SH "成员函数说明"
.PP 
.SS "std::string S3GF::Logger::lastError ()\fR [inline]\fP, \fR [static]\fP"

.SS "void S3GF::Logger::log (const std::string & message, \fBLogLevel\fP level = \fR\fBDEBUG\fP\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBLogger\fP & S3GF::Logger::operator= (const \fBLogger\fP & )\fR [delete]\fP"

.SS "\fBLogger\fP & S3GF::Logger::operator= (\fBLogger\fP && )\fR [delete]\fP"

.SS "void S3GF::Logger::setBaseLogLevel (\fBLogLevel\fP level)\fR [inline]\fP, \fR [static]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
