.TH "S3GF::TasksManager::TaskCmp" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TasksManager::TaskCmp
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ThreadPool\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBTask\fP &t1, \fBTask\fP &t2)"
.br
.in -1c
.SH "成员函数说明"
.PP 
.SS "bool S3GF::TasksManager::TaskCmp::operator() (\fBTask\fP & t1, \fBTask\fP & t2)\fR [inline]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
