.TH "S3GF::Vector2" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Vector2 \- 向量坐标  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBVector2\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "void \fBreset\fP (float \fBx\fP, float \fBy\fP)"
.br
.RI "重新设置新的向量 "
.ti -1c
.RI "void \fBreset\fP (const \fBVector2\fP &vector2)"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator+\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator\-\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator*\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator*\fP (float v) const"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator/\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator/\fP (float v) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBVector2\fP &v)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBVector2\fP &v)"
.br
.ti -1c
.RI "void \fBoperator*=\fP (const \fBVector2\fP &v)"
.br
.ti -1c
.RI "void \fBoperator*=\fP (float v)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (const \fBVector2\fP &v)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (float v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBVector2\fP &v) const"
.br
.ti -1c
.RI "bool \fBisEqual\fP (const \fBVector2\fP &v, const float EPISON=1e\-6f) const"
.br
.RI "判断两个坐标位置是否大致相等 "
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "详细描述"
.PP 
向量坐标 

用于指定某对象的位置 
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Vector2::Vector2 ()\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::Vector2::Vector2 (float x, float y)\fR [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "bool S3GF::Vector2::isEqual (const \fBVector2\fP & v, const float EPISON = \fR1e\-6f\fP) const\fR [inline]\fP, \fR [nodiscard]\fP"

.PP
判断两个坐标位置是否大致相等 
.PP
\fB参数\fP
.RS 4
\fIv\fP 指定另一个坐标 
.br
\fIEPISON\fP 允许的误差数 （默认 0\&.000001f 误差） 
.RE
.PP
\fB返回值\fP
.RS 4
\fItrue\fP 表示相等 
.br
\fIfalse\fP 表示不相等 
.RE
.PP

.SS "bool S3GF::Vector2::operator!= (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "\fBVector2\fP S3GF::Vector2::operator* (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "\fBVector2\fP S3GF::Vector2::operator* (float v) const\fR [inline]\fP"

.SS "void S3GF::Vector2::operator*= (const \fBVector2\fP & v)\fR [inline]\fP"

.SS "void S3GF::Vector2::operator*= (float v)\fR [inline]\fP"

.SS "\fBVector2\fP S3GF::Vector2::operator+ (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "void S3GF::Vector2::operator+= (const \fBVector2\fP & v)\fR [inline]\fP"

.SS "\fBVector2\fP S3GF::Vector2::operator\- (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "void S3GF::Vector2::operator\-= (const \fBVector2\fP & v)\fR [inline]\fP"

.SS "\fBVector2\fP S3GF::Vector2::operator/ (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "\fBVector2\fP S3GF::Vector2::operator/ (float v) const\fR [inline]\fP"

.SS "void S3GF::Vector2::operator/= (const \fBVector2\fP & v)\fR [inline]\fP"

.SS "void S3GF::Vector2::operator/= (float v)\fR [inline]\fP"

.SS "bool S3GF::Vector2::operator< (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "bool S3GF::Vector2::operator<= (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "bool S3GF::Vector2::operator== (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "bool S3GF::Vector2::operator> (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "bool S3GF::Vector2::operator>= (const \fBVector2\fP & v) const\fR [inline]\fP"

.SS "void S3GF::Vector2::reset (const \fBVector2\fP & vector2)\fR [inline]\fP"

.SS "void S3GF::Vector2::reset (float x, float y)\fR [inline]\fP"

.PP
重新设置新的向量 
.PP
\fB参数\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.RE
.PP

.SH "类成员变量说明"
.PP 
.SS "float S3GF::Vector2::x"

.SS "float S3GF::Vector2::y"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
