.TH "S3GF::Renderer" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Renderer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBRenderer\fP (\fBWindow\fP *\fBwindow\fP=nullptr)"
.br
.ti -1c
.RI "\fB~Renderer\fP ()"
.br
.ti -1c
.RI "SDL_Renderer * \fBself\fP () const"
.br
.ti -1c
.RI "\fBWindow\fP * \fBwindow\fP () const"
.br
.ti -1c
.RI "void \fB_update\fP ()"
.br
.ti -1c
.RI "void \fBfillBackground\fP (const SDL_Color &color, bool covered=false)"
.br
.ti -1c
.RI "void \fBdrawPoint\fP (const \fBGraphics::Point\fP &point)"
.br
.ti -1c
.RI "void \fBdrawPoint\fP (\fBGraphics::Point\fP &&point)"
.br
.ti -1c
.RI "void \fBdrawLine\fP (const \fBGraphics::Line\fP &line)"
.br
.ti -1c
.RI "void \fBdrawLine\fP (\fBGraphics::Line\fP &&line)"
.br
.ti -1c
.RI "void \fBdrawRectangle\fP (const \fBGraphics::Rectangle\fP &rectangle)"
.br
.ti -1c
.RI "void \fBdrawRectangle\fP (\fBGraphics::Rectangle\fP &&rectangle)"
.br
.ti -1c
.RI "void \fBdrawTriangle\fP (const \fBGraphics::Triangle\fP &triangle)"
.br
.ti -1c
.RI "void \fBdrawTriangle\fP (\fBGraphics::Triangle\fP &&triangle)"
.br
.ti -1c
.RI "void \fBdrawEllipse\fP (const \fBGraphics::Ellipse\fP &ellipse)"
.br
.ti -1c
.RI "void \fBdrawEllipse\fP (\fBGraphics::Ellipse\fP &&ellipse)"
.br
.ti -1c
.RI "void \fBdrawTexture\fP (SDL_Texture *texture, \fBProperty\fP *property)"
.br
.ti -1c
.RI "void \fBdrawText\fP (TTF_Text *text, const \fBVector2\fP &position)"
.br
.ti -1c
.RI "void \fBsetViewport\fP (const \fBGeometry\fP &geometry)"
.br
.ti -1c
.RI "void \fBsetClipView\fP (const \fBGeometry\fP &geometry)"
.br
.ti -1c
.RI "void \fBsetBlendMode\fP (const SDL_BlendMode &blend_mode)"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Renderer::Renderer (\fBWindow\fP * window = \fRnullptr\fP)\fR [explicit]\fP"

.SS "S3GF::Renderer::~Renderer ()"

.SH "成员函数说明"
.PP 
.SS "void S3GF::Renderer::_update ()"

.SS "void S3GF::Renderer::drawEllipse (const \fBGraphics::Ellipse\fP & ellipse)"

.SS "void S3GF::Renderer::drawEllipse (\fBGraphics::Ellipse\fP && ellipse)"

.SS "void S3GF::Renderer::drawLine (const \fBGraphics::Line\fP & line)"

.SS "void S3GF::Renderer::drawLine (\fBGraphics::Line\fP && line)"

.SS "void S3GF::Renderer::drawPoint (const \fBGraphics::Point\fP & point)"

.SS "void S3GF::Renderer::drawPoint (\fBGraphics::Point\fP && point)"

.SS "void S3GF::Renderer::drawRectangle (const \fBGraphics::Rectangle\fP & rectangle)"

.SS "void S3GF::Renderer::drawRectangle (\fBGraphics::Rectangle\fP && rectangle)"

.SS "void S3GF::Renderer::drawText (TTF_Text * text, const \fBVector2\fP & position)"

.SS "void S3GF::Renderer::drawTexture (SDL_Texture * texture, \fBProperty\fP * property)"

.SS "void S3GF::Renderer::drawTriangle (const \fBGraphics::Triangle\fP & triangle)"

.SS "void S3GF::Renderer::drawTriangle (\fBGraphics::Triangle\fP && triangle)"

.SS "void S3GF::Renderer::fillBackground (const SDL_Color & color, bool covered = \fRfalse\fP)"

.SS "SDL_Renderer * S3GF::Renderer::self () const"

.SS "void S3GF::Renderer::setBlendMode (const SDL_BlendMode & blend_mode)"

.SS "void S3GF::Renderer::setClipView (const \fBGeometry\fP & geometry)"

.SS "void S3GF::Renderer::setViewport (const \fBGeometry\fP & geometry)"

.SS "\fBWindow\fP * S3GF::Renderer::window () const"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
