.TH "S3GF::TextSystem::Text" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TextSystem::Text
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "TTF_Text * \fBself\fP"
.br
.ti -1c
.RI "std::string \fBtext\fP"
.br
.ti -1c
.RI "std::string \fBfont_name\fP"
.br
.ti -1c
.RI "SDL_Color \fBfont_color\fP {\fBStdColor::Black\fP}"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "SDL_Color S3GF::TextSystem::Text::font_color {\fBStdColor::Black\fP}"

.SS "std::string S3GF::TextSystem::Text::font_name"

.SS "TTF_Text* S3GF::TextSystem::Text::self"

.SS "std::string S3GF::TextSystem::Text::text"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
