.TH "S3GF::TasksManager::Task" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TasksManager::Task
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ThreadPool\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "\fBPriority\fP \fBpriority\fP"
.br
.ti -1c
.RI "std::function< void()> \fBfunction\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "std::function<void()> S3GF::TasksManager::Task::function"

.SS "uint64_t S3GF::TasksManager::Task::id"

.SS "\fBPriority\fP S3GF::TasksManager::Task::priority"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
