.TH "S3GF::Graphics::Point" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Graphics::Point
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBPoint\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP (float x, float y, uint16_t \fBsize\fP=1, const SDL_Color &\fBcolor\fP=\fBRGBAColor::Black\fP, uint16_t count=32)"
.br
.ti -1c
.RI "void \fBmove\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBmove\fP (const \fBVector2\fP &new_pos)"
.br
.ti -1c
.RI "void \fBresize\fP (uint16_t new_size)"
.br
.ti -1c
.RI "void \fBsetColor\fP (const SDL_Color &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBsetSegment\fP (uint16_t segment=32)"
.br
.ti -1c
.RI "void \fBreset\fP (const \fBVector2\fP &pos, uint16_t \fBsize\fP, const SDL_Color &\fBcolor\fP, uint16_t segment=32)"
.br
.ti -1c
.RI "void \fBreset\fP (float x, float y, uint16_t \fBsize\fP, const SDL_Color &\fBcolor\fP, uint16_t segment=32)"
.br
.ti -1c
.RI "const \fBVector2\fP & \fBposition\fP () const"
.br
.ti -1c
.RI "uint16_t \fBsize\fP () const"
.br
.ti -1c
.RI "const SDL_Color & \fBcolor\fP () const"
.br
.ti -1c
.RI "const SDL_Vertex * \fBvertices\fP () const"
.br
.ti -1c
.RI "const int * \fBindices\fP () const"
.br
.ti -1c
.RI "size_t \fBverticesCount\fP () const"
.br
.ti -1c
.RI "size_t \fBindicesCount\fP () const"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Graphics::Point::Point ()\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::Graphics::Point::Point (float x, float y, uint16_t size = \fR1\fP, const SDL_Color & color = \fR\fBRGBAColor::Black\fP\fP, uint16_t count = \fR32\fP)\fR [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "const SDL_Color & S3GF::Graphics::Point::color () const\fR [inline]\fP"

.SS "const int * S3GF::Graphics::Point::indices () const\fR [inline]\fP"

.SS "size_t S3GF::Graphics::Point::indicesCount () const\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::move (const \fBVector2\fP & new_pos)\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::move (float x, float y)\fR [inline]\fP"

.SS "const \fBVector2\fP & S3GF::Graphics::Point::position () const\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::reset (const \fBVector2\fP & pos, uint16_t size, const SDL_Color & color, uint16_t segment = \fR32\fP)\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::reset (float x, float y, uint16_t size, const SDL_Color & color, uint16_t segment = \fR32\fP)\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::resize (uint16_t new_size)\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::setColor (const SDL_Color & color)\fR [inline]\fP"

.SS "void S3GF::Graphics::Point::setSegment (uint16_t segment = \fR32\fP)\fR [inline]\fP"

.SS "uint16_t S3GF::Graphics::Point::size () const\fR [inline]\fP"

.SS "const SDL_Vertex * S3GF::Graphics::Point::vertices () const\fR [inline]\fP"

.SS "size_t S3GF::Graphics::Point::verticesCount () const\fR [inline]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
