.TH "S3GF::ColorStatus" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::ColorStatus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Control\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "SDL_Color \fBnormal\fP"
.br
.ti -1c
.RI "SDL_Color \fBactive\fP"
.br
.ti -1c
.RI "SDL_Color \fBpressed\fP"
.br
.ti -1c
.RI "SDL_Color \fBinvalid\fP"
.br
.ti -1c
.RI "SDL_Color \fBchecked\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "SDL_Color S3GF::ColorStatus::active"

.SS "SDL_Color S3GF::ColorStatus::checked"

.SS "SDL_Color S3GF::ColorStatus::invalid"

.SS "SDL_Color S3GF::ColorStatus::normal"

.SS "SDL_Color S3GF::ColorStatus::pressed"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
