.TH "S3GF::Matrix2D< T >" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Matrix2D< T > \- 二维矩阵  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "类"

.in +1c
.ti -1c
.RI "struct \fBPosition\fP"
.br
.in -1c
.SS "Public 类型"

.in +1c
.ti -1c
.RI "using \fBiterator\fP = typename std::vector<T>::iterator"
.br
.ti -1c
.RI "using \fBconstIterator\fP = typename std::vector<T>::const_iterator"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBMatrix2D\fP ()"
.br
.RI "创建一个空白的二维矩阵（没有任何数据） "
.ti -1c
.RI "\fBMatrix2D\fP (uint32_t row, uint32_t col, const std::function< void(T &)> &deleter={})"
.br
.RI "创建指定行列的二维矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP (uint32_t row, uint32_t col, const T &value, const std::function< void(T &)> &deleter={})"
.br
.RI "创建指定行列与默认值的二维矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP (const \fBMatrix2D\fP< T > &matrix)"
.br
.RI "复制原有的二维矩阵 "
.ti -1c
.RI "\fB~Matrix2D\fP ()"
.br
.ti -1c
.RI "void \fBsetDeleter\fP (const std::function< void(T &)> &function)"
.br
.RI "设置删除器 "
.ti -1c
.RI "void \fBfill\fP (const T &value)"
.br
.RI "填充所有值 "
.ti -1c
.RI "bool \fBfillN\fP (const \fBMatrix2D::Position\fP &start, const \fBMatrix2D::Position\fP &\fBend\fP, const T &value)"
.br
.RI "填充范围内的值 "
.ti -1c
.RI "void \fBresize\fP (uint32_t line, uint32_t col)"
.br
.RI "重新调整新的大小 "
.ti -1c
.RI "T & \fBat\fP (uint32_t row, uint32_t col)"
.br
.RI "获取矩阵中指定行列的数据 "
.ti -1c
.RI "const T & \fBget\fP (uint32_t row, uint32_t col)"
.br
.RI "获取矩阵中指定行列的数据 "
.ti -1c
.RI "uint32_t \fBrows\fP () const"
.br
.RI "获取当前矩阵的总行数 "
.ti -1c
.RI "uint32_t \fBcols\fP () const"
.br
.RI "获取当前矩阵的总列数 "
.ti -1c
.RI "\fBMatrix2D\fP \fBoperator+\fP (const \fBMatrix2D\fP< T > &other) const"
.br
.ti -1c
.RI "\fBMatrix2D\fP \fBoperator\-\fP (const \fBMatrix2D\fP< T > &other) const"
.br
.ti -1c
.RI "\fBMatrix2D\fP \fBoperator*\fP (const \fBMatrix2D\fP< T > &other) const"
.br
.RI "矩阵乘法 "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMatrix2D\fP< T > &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBMatrix2D\fP< T > &other) const"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (uint32_t index)"
.br
.ti -1c
.RI "T & \fBoperator()\fP (uint32_t row, uint32_t col)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBconstIterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBconstIterator\fP \fBend\fP () const"
.br
.ti -1c
.RI "void \fBadd\fP (T &value, const std::function< void(T &, T &)> &function={})"
.br
.RI "全局相加 "
.ti -1c
.RI "void \fBadd\fP (T &&value, const std::function< void(T &, T &)> &function={})"
.br
.RI "全局相加 "
.ti -1c
.RI "void \fBminus\fP (T &value, const std::function< void(T &, T &)> &function={})"
.br
.RI "全局相减 "
.ti -1c
.RI "void \fBminus\fP (T &&value, const std::function< void(T &, T &)> &function={})"
.br
.RI "全局相减 "
.ti -1c
.RI "void \fBtimes\fP (T &value, const std::function< void(T &, T &)> &function={})"
.br
.RI "全局乘法 "
.ti -1c
.RI "void \fBtimes\fP (T &&value, const std::function< void(T &, T &)> &function={})"
.br
.RI "全局点乘 "
.ti -1c
.RI "void \fBtimes\fP (const \fBMatrix2D\fP< T > &other, const std::function< void(T &, const T &)> &function={})"
.br
.RI "矩阵点乘 "
.ti -1c
.RI "void \fBmultiply\fP (const \fBMatrix2D\fP< T > &other)"
.br
.RI "矩阵乘法 "
.ti -1c
.RI "void \fBtranspose\fP ()"
.br
.RI "转置矩阵 "
.ti -1c
.RI "void \fBreverse\fP (bool reverse_row=true, bool reverse_col=false)"
.br
.RI "翻转矩阵 "
.ti -1c
.RI "void \fBrotate\fP (bool turn_right=true)"
.br
.RI "旋转矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP \fBsplitRows\fP (uint32_t start_row, uint32_t end_row)"
.br
.RI "切割指定行矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP \fBsplitCols\fP (uint32_t start_col, uint32_t end_col)"
.br
.RI "切割指定列矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP \fBsplit\fP (uint32_t \fBrows\fP, uint32_t \fBcols\fP, const \fBPosition\fP &start_pos)"
.br
.RI "切割矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP \fBsplit\fP (\fBMatrix2D::Position\fP start_pos, \fBMatrix2D::Position\fP end_pos)"
.br
.RI "按照矩形的方式切割矩阵 "
.ti -1c
.RI "\fBMatrix2D\fP< T > \fBinverse\fP ()"
.br
.RI "逆矩阵 "
.in -1c
.SH "详细描述"
.PP 

.SS "template<typename T>
.br
struct S3GF::Matrix2D< T >"二维矩阵 


.PP
\fB自从\fP
.RS 4
v1\&.1\&.0-alpha
.RE
.PP
支持使用基本数据类型及简单的结构体进行存储。 
.SH "成员类型定义说明"
.PP 
.SS "template<typename T> using \fBS3GF::Matrix2D\fP< T >::constIterator = typename std::vector<T>::const_iterator"

.SS "template<typename T> using \fBS3GF::Matrix2D\fP< T >::iterator = typename std::vector<T>::iterator"

.SH "构造及析构函数说明"
.PP 
.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Matrix2D ()\fR [inline]\fP, \fR [explicit]\fP"

.PP
创建一个空白的二维矩阵（没有任何数据） 
.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Matrix2D (uint32_t row, uint32_t col, const std::function< void(T &)> & deleter = \fR{}\fP)"

.PP
创建指定行列的二维矩阵 
.PP
\fB参数\fP
.RS 4
\fIrow\fP 行 
.br
\fIcol\fP 列 
.br
\fIdeleter\fP 删除器（若需要删除指针等情况时指定） 
.RE
.PP

.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Matrix2D (uint32_t row, uint32_t col, const T & value, const std::function< void(T &)> & deleter = \fR{}\fP)"

.PP
创建指定行列与默认值的二维矩阵 
.PP
\fB参数\fP
.RS 4
\fIrow\fP 行 
.br
\fIcol\fP 列 
.br
\fIvalue\fP 默认值（用于填充所有数据） 
.br
\fIdeleter\fP 删除器（若需要删除指针等情况时指定） 
.RE
.PP

.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::Matrix2D (const \fBMatrix2D\fP< T > & matrix)"

.PP
复制原有的二维矩阵 
.PP
\fB参数\fP
.RS 4
\fImatrix\fP 指定二维矩阵 
.RE
.PP

.SS "template<typename T> \fBS3GF::Matrix2D\fP< T >::~\fBMatrix2D\fP ()"

.SH "成员函数说明"
.PP 
.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::add (T && value, const std::function< void(T &, T &)> & function = \fR{}\fP)"

.PP
全局相加 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定）
.RE
.PP
将矩阵里的所有值进行相加操作 
.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::add (T & value, const std::function< void(T &, T &)> & function = \fR{}\fP)"

.PP
全局相加 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定）
.RE
.PP
将矩阵里的所有值进行相加操作 
.SS "template<typename T> T & \fBS3GF::Matrix2D\fP< T >::at (uint32_t row, uint32_t col)"

.PP
获取矩阵中指定行列的数据 
.PP
\fB参数\fP
.RS 4
\fIrow\fP 行 
.br
\fIcol\fP 列 
.RE
.PP
\fB返回\fP
.RS 4
返回对应行列下的数据 
.RE
.PP
\fB参见\fP
.RS 4
\fBget\fP 
.RE
.PP

.SS "template<typename T> \fBiterator\fP \fBS3GF::Matrix2D\fP< T >::begin ()\fR [inline]\fP"

.SS "template<typename T> \fBconstIterator\fP \fBS3GF::Matrix2D\fP< T >::begin () const\fR [inline]\fP"

.SS "template<typename T> uint32_t \fBS3GF::Matrix2D\fP< T >::cols () const\fR [nodiscard]\fP"

.PP
获取当前矩阵的总列数 
.PP
\fB返回\fP
.RS 4
返回对应的列数 
.RE
.PP

.SS "template<typename T> \fBiterator\fP \fBS3GF::Matrix2D\fP< T >::end ()\fR [inline]\fP"

.SS "template<typename T> \fBconstIterator\fP \fBS3GF::Matrix2D\fP< T >::end () const\fR [inline]\fP"

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::fill (const T & value)"

.PP
填充所有值 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.RE
.PP

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::fillN (const \fBMatrix2D\fP< T >::Position & start, const \fBMatrix2D\fP< T >::Position & end, const T & value)"

.PP
填充范围内的值 
.PP
\fB参数\fP
.RS 4
\fIstart\fP 指定开始位置（行列） 
.br
\fIend\fP 指定结束位置（行列） 
.br
\fIvalue\fP 指定填充的值 
.RE
.PP

.SS "template<typename T> const T & \fBS3GF::Matrix2D\fP< T >::get (uint32_t row, uint32_t col)"

.PP
获取矩阵中指定行列的数据 
.PP
\fB参数\fP
.RS 4
\fIrow\fP 行 
.br
\fIcol\fP 列 
.RE
.PP
\fB返回\fP
.RS 4
返回对应行列下的数据 
.RE
.PP
\fB注解\fP
.RS 4
区别于 \fRat\fP，此函数为常量版本，无法修改里面的数据！ 
.RE
.PP
\fB参见\fP
.RS 4
\fBat\fP 
.RE
.PP

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::inverse ()"

.PP
逆矩阵 
.PP
\fB返回\fP
.RS 4
返回新的矩阵，用于存储求得的结果 
.RE
.PP
\fB注解\fP
.RS 4
当前仅支持整数、浮点数运算，不支持其它数据类型的运算！ 

.PP
两个矩阵的大小必需完全一致！否则将返回空矩阵！ 
.RE
.PP

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::minus (T && value, const std::function< void(T &, T &)> & function = \fR{}\fP)"

.PP
全局相减 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定）
.RE
.PP
将矩阵里的所有值进行相减操作 
.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::minus (T & value, const std::function< void(T &, T &)> & function = \fR{}\fP)"

.PP
全局相减 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定）
.RE
.PP
将矩阵里的所有值进行相减操作 
.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::multiply (const \fBMatrix2D\fP< T > & other)"

.PP
矩阵乘法 将矩阵里的所有值进行乘法操作 
.PP
\fB参数\fP
.RS 4
\fIother\fP 指定矩阵，其指定的行数必需与现有的列数相等 
.RE
.PP
\fB注解\fP
.RS 4
当前仅支持整数、浮点数运算，不支持其它数据类型的运算！ 

.PP
两个矩阵必需分别为 m * n, n * p 的大小才可用！ 
.RE
.PP

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::operator!= (const \fBMatrix2D\fP< T > & other) const"

.SS "template<typename T> T & \fBS3GF::Matrix2D\fP< T >::operator() (uint32_t row, uint32_t col)"

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::operator* (const \fBMatrix2D\fP< T > & other) const"

.PP
矩阵乘法 
.PP
\fB参数\fP
.RS 4
\fIother\fP 指定矩阵，其指定的行数必需与现有的列数相等
.RE
.PP
将矩阵里的所有值进行乘法操作 
.PP
\fB注解\fP
.RS 4
当前仅支持整数、浮点数运算，不支持其它数据类型的运算！ 

.PP
两个矩阵必需分别为 m * n, n * p 的大小才可用！ 
.RE
.PP

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::operator+ (const \fBMatrix2D\fP< T > & other) const"

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::operator\- (const \fBMatrix2D\fP< T > & other) const"

.SS "template<typename T> bool \fBS3GF::Matrix2D\fP< T >::operator== (const \fBMatrix2D\fP< T > & other) const"

.SS "template<typename T> T & \fBS3GF::Matrix2D\fP< T >::operator[] (uint32_t index)"

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::resize (uint32_t line, uint32_t col)"

.PP
重新调整新的大小 
.PP
\fB参数\fP
.RS 4
\fIline\fP 行 
.br
\fIcol\fP 列 
.RE
.PP

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::reverse (bool reverse_row = \fRtrue\fP, bool reverse_col = \fRfalse\fP)"

.PP
翻转矩阵 当选择任何一个方向的逆序时，都会发生交换。 
.PP
\fB参数\fP
.RS 4
\fIreverse_row\fP 行与行之间逆序（垂直翻转） 
.br
\fIreverse_col\fP 列与列之间逆序（水平翻转） 
.RE
.PP
\fB注解\fP
.RS 4
当两个参数都为 \fRtrue\fP 时，矩阵将完全逆序 
.RE
.PP
\fB参见\fP
.RS 4
\fBrotate\fP 
.RE
.PP

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::rotate (bool turn_right = \fRtrue\fP)"

.PP
旋转矩阵 
.PP
\fB参数\fP
.RS 4
\fIturn_right\fP 是否向右旋转 90°，反之向左旋转 90° 
.RE
.PP
\fB参见\fP
.RS 4
\fBreverse\fP 

.PP
\fBtranspose\fP 
.RE
.PP

.SS "template<typename T> uint32_t \fBS3GF::Matrix2D\fP< T >::rows () const\fR [nodiscard]\fP"

.PP
获取当前矩阵的总行数 
.PP
\fB返回\fP
.RS 4
返回对应的行数 
.RE
.PP

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::setDeleter (const std::function< void(T &)> & function)"

.PP
设置删除器 
.PP
\fB参数\fP
.RS 4
\fIfunction\fP 指定函数
.RE
.PP
当此类析构时，将调用删除器以删除指针！ 
.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::split (\fBMatrix2D\fP< T >::Position start_pos, \fBMatrix2D\fP< T >::Position end_pos)"

.PP
按照矩形的方式切割矩阵 根据起始位置和结束位置包围成一个矩形，并将其切割成独立的矩阵。 
.PP
\fB参数\fP
.RS 4
\fIstart_pos\fP 起始位置 
.br
\fIend_pos\fP 结束位置 
.RE
.PP
\fB返回\fP
.RS 4
返回切割后的矩阵。 
.RE
.PP

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::split (uint32_t rows, uint32_t cols, const \fBPosition\fP & start_pos)"

.PP
切割矩阵 切割原有的矩阵，根据 \fRstart_pos\fP 位置开始，取 \fRrows * cols\fP 个数据并创建成新的矩阵。 
.PP
\fB参数\fP
.RS 4
\fIrows\fP 新的行数 
.br
\fIcols\fP 新的列数 
.br
\fIstart_pos\fP 从哪个位置开始 
.RE
.PP
\fB返回\fP
.RS 4
返回新的大小为 \fR(rows * cols)\fP 的二维矩阵。
.RE
.PP
\fB注解\fP
.RS 4
从 \fRstart_pos\fP 位置起，若取得数据的总个数小于新的矩阵大小，则剩余部分自动填充为空数据。 

.PP
指定的 \fRstart_pos\fP 位置若超出原有矩阵的范围，将返回空矩阵。 
.RE
.PP

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::splitCols (uint32_t start_col, uint32_t end_col)"

.PP
切割指定列矩阵 
.PP
\fB参数\fP
.RS 4
\fIstart_col\fP 起始列 
.br
\fIend_col\fP 结束列 
.RE
.PP
\fB返回\fP
.RS 4
返回矩阵行位于 \fR[start_col, end_col)\fP 区间内的所有列矩阵 
.RE
.PP

.SS "template<typename T> \fBMatrix2D\fP< T > \fBS3GF::Matrix2D\fP< T >::splitRows (uint32_t start_row, uint32_t end_row)"

.PP
切割指定行矩阵 
.PP
\fB参数\fP
.RS 4
\fIstart_row\fP 起始行 
.br
\fIend_row\fP 结束行 
.RE
.PP
\fB返回\fP
.RS 4
返回矩阵行位于 \fR[start_row, end_row)\fP 区间内的所有行矩阵 
.RE
.PP

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::times (const \fBMatrix2D\fP< T > & other, const std::function< void(T &, const T &)> & function = \fR{}\fP)"

.PP
矩阵点乘 
.PP
\fB参数\fP
.RS 4
\fIother\fP 指定矩阵 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定） 
.RE
.PP
\fB注解\fP
.RS 4
两个矩阵的大小必需完全一样（即行列必需相等）！ 
.RE
.PP

.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::times (T && value, const std::function< void(T &, T &)> & function = \fR{}\fP)"

.PP
全局点乘 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定）
.RE
.PP
将矩阵里的所有值进行点乘操作 
.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::times (T & value, const std::function< void(T &, T &)> & function = \fR{}\fP)"

.PP
全局乘法 
.PP
\fB参数\fP
.RS 4
\fIvalue\fP 指定值 
.br
\fIfunction\fP 函数（对于复杂的数据类型，此参数必需指定）
.RE
.PP
将矩阵里的所有值进行相乘操作 
.SS "template<typename T> void \fBS3GF::Matrix2D\fP< T >::transpose ()"

.PP
转置矩阵 将原有的 m * n 大小的矩阵转置为 n * m 大小的矩阵。 
.PP
\fB参见\fP
.RS 4
\fBrotate\fP 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
