.TH "S3GF::Cursor" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Cursor \- 鼠标光标  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Cursor\&.h>\fP
.SS "类"

.in +1c
.ti -1c
.RI "struct \fBUserCustom\fP"
.br
.RI "用户自定义鼠标光标数据 "
.in -1c
.SS "Public 类型"

.in +1c
.ti -1c
.RI "enum \fBStdCursor\fP { \fBDefault\fP = 0x00, \fBNormal\fP = 0x00, \fBEdit\fP = 0x01, \fBWait\fP = 0x02, \fBCrosshair\fP = 0x03, \fBBusy\fP = 0x04, \fBResize_NWSE\fP = 0x05, \fBResize_NESW\fP = 0x06, \fBResize_Horizontal\fP = 0x07, \fBResize_EW\fP = 0x07, \fBResize_Vertical\fP = 0x08, \fBResize_NS\fP = 0x08, \fBMove\fP = 0x09, \fBNot_Allowed\fP = 0x0a, \fBForbidden\fP = 0x0a, \fBHand\fP = 0x0b, \fBPointer\fP = 0x0b, \fBResize_NW\fP = 0x0c, \fBResize_N\fP = 0x0d, \fBResize_NE\fP = 0x0e, \fBResize_E\fP = 0x0f, \fBResize_SE\fP = 0x10, \fBResize_S\fP = 0x11, \fBResize_SW\fP = 0x12, \fBResize_W\fP = 0x13, \fBCount\fP = 0x14, \fBCustom\fP = 0x15 }"
.br
.RI "标准鼠标光标样式 "
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBCursor\fP (const \fBCursor\fP &)=delete"
.br
.ti -1c
.RI "\fBCursor\fP (\fBCursor\fP &&)=delete"
.br
.ti -1c
.RI "\fBCursor\fP & \fBoperator=\fP (const \fBCursor\fP &)=delete"
.br
.ti -1c
.RI "\fBCursor\fP & \fBoperator=\fP (\fBCursor\fP &&)=delete"
.br
.ti -1c
.RI "\fB~Cursor\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP \fBglobalPosition\fP () const"
.br
.RI "获取鼠标光标在显示器中所在的位置 "
.ti -1c
.RI "\fBVector2\fP \fBposition\fP () const"
.br
.RI "获取鼠标光标在获得焦点的窗口下的位置 "
.ti -1c
.RI "uint64_t \fBfocusOn\fP () const"
.br
.RI "获取鼠标当前聚焦于哪个窗口 "
.ti -1c
.RI "void \fBmove\fP (const \fBVector2\fP &pos, const \fBWindow\fP *window=nullptr)"
.br
.RI "移动鼠标光标至指定位置 "
.ti -1c
.RI "void \fBmove\fP (float x, float y, const \fBWindow\fP *window=nullptr)"
.br
.RI "移动光标至指定位置 "
.ti -1c
.RI "void \fBmoveToCenter\fP (const \fBWindow\fP *window=nullptr)"
.br
.RI "将鼠标光标移动至画面中心点 "
.ti -1c
.RI "void \fBsetCursor\fP (const \fBStdCursor\fP &\fBcursor\fP)"
.br
.RI "设置鼠标光标 "
.ti -1c
.RI "void \fBsetCursor\fP (const std::string &path, int hot_x, int hot_y)"
.br
.RI "设置自定义鼠标光标 "
.ti -1c
.RI "void \fBsetUserCustomEnabled\fP (bool enabled)"
.br
.RI "是否允许使用自定义鼠标光标 "
.ti -1c
.RI "bool \fBuserCustomEnabled\fP () const"
.br
.RI "当前是否使用自定义鼠标光标 "
.ti -1c
.RI "void \fBsetCustomCursor\fP (const \fBStdCursor\fP &stdCursor, const std::string &path, const \fBUserCustom::HotPoint\fP &hot_point)"
.br
.RI "设置自定义鼠标光标 "
.ti -1c
.RI "\fBStdCursor\fP \fBcursor\fP () const"
.br
.RI "获取当前鼠标光标样式 "
.ti -1c
.RI "void \fBsetVisible\fP (bool \fBvisible\fP)"
.br
.RI "显示/隐藏鼠标光标 "
.ti -1c
.RI "bool \fBvisible\fP () const"
.br
.RI "获取当前鼠标光标是否显示 "
.ti -1c
.RI "void \fBunload\fP ()"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static \fBCursor\fP * \fBglobal\fP ()"
.br
.RI "获取鼠标光标全局 "
.in -1c
.SH "详细描述"
.PP 
鼠标光标 

用于全局控制鼠标光标的位置、样式 
.PP
\fB注解\fP
.RS 4
需要使用 \fR\fBglobal()\fP\fP 获取全局 
.RE
.PP

.SH "成员枚举类型说明"
.PP 
.SS "enum \fBS3GF::Cursor::StdCursor\fP"

.PP
标准鼠标光标样式 获取系统下当前使用的鼠标光标 
.PP
\fB枚举值\fP
.in +1c
.TP
\f(BIDefault \fP
.TP
\f(BINormal \fP
.TP
\f(BIEdit \fP
.TP
\f(BIWait \fP
.TP
\f(BICrosshair \fP
.TP
\f(BIBusy \fP
.TP
\f(BIResize_NWSE \fP
.TP
\f(BIResize_NESW \fP
.TP
\f(BIResize_Horizontal \fP
.TP
\f(BIResize_EW \fP
.TP
\f(BIResize_Vertical \fP
.TP
\f(BIResize_NS \fP
.TP
\f(BIMove \fP
.TP
\f(BINot_Allowed \fP
.TP
\f(BIForbidden \fP
.TP
\f(BIHand \fP
.TP
\f(BIPointer \fP
.TP
\f(BIResize_NW \fP
.TP
\f(BIResize_N \fP
.TP
\f(BIResize_NE \fP
.TP
\f(BIResize_E \fP
.TP
\f(BIResize_SE \fP
.TP
\f(BIResize_S \fP
.TP
\f(BIResize_SW \fP
.TP
\f(BIResize_W \fP
.TP
\f(BICount \fP
.TP
\f(BICustom \fP
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Cursor::Cursor (const \fBCursor\fP & )\fR [explicit]\fP, \fR [delete]\fP"

.SS "S3GF::Cursor::Cursor (\fBCursor\fP && )\fR [explicit]\fP, \fR [delete]\fP"

.SS "S3GF::Cursor::~Cursor ()\fR [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "\fBStdCursor\fP S3GF::Cursor::cursor () const\fR [inline]\fP"

.PP
获取当前鼠标光标样式 
.SS "uint64_t S3GF::Cursor::focusOn () const\fR [inline]\fP"

.PP
获取鼠标当前聚焦于哪个窗口 
.PP
\fB返回\fP
.RS 4
返回鼠标所在的窗口 ID 
.RE
.PP

.SS "\fBCursor\fP * S3GF::Cursor::global ()\fR [inline]\fP, \fR [static]\fP"

.PP
获取鼠标光标全局 
.SS "\fBVector2\fP S3GF::Cursor::globalPosition () const\fR [inline]\fP"

.PP
获取鼠标光标在显示器中所在的位置 
.PP
\fB返回\fP
.RS 4
返回全局坐标 
.RE
.PP
\fB参见\fP
.RS 4
\fBposition\fP 

.PP
\fBmove\fP 
.RE
.PP

.SS "void S3GF::Cursor::move (const \fBVector2\fP & pos, const \fBWindow\fP * window = \fRnullptr\fP)\fR [inline]\fP"

.PP
移动鼠标光标至指定位置 
.PP
\fB参数\fP
.RS 4
\fIpos\fP 指定位置 
.br
\fIwindow\fP 指定窗口 
.RE
.PP
\fB注解\fP
.RS 4
若不指定 window 参数，将默认以全局显示器屏幕为主。 
.RE
.PP
\fB参见\fP
.RS 4
\fBposition\fP 

.PP
\fBglobalPosition\fP 
.RE
.PP

.SS "void S3GF::Cursor::move (float x, float y, const \fBWindow\fP * window = \fRnullptr\fP)\fR [inline]\fP"

.PP
移动光标至指定位置 
.PP
\fB参数\fP
.RS 4
\fIx\fP 指定横坐标 
.br
\fIy\fP 指定纵坐标 
.br
\fIwindow\fP 指定窗口 
.RE
.PP
\fB注解\fP
.RS 4
若不指定 window 参数，将默认以全局显示器屏幕为主。 
.RE
.PP
\fB参见\fP
.RS 4
\fBposition\fP 

.PP
\fBglobalPosition\fP 
.RE
.PP

.SS "void S3GF::Cursor::moveToCenter (const \fBWindow\fP * window = \fRnullptr\fP)\fR [inline]\fP"

.PP
将鼠标光标移动至画面中心点 
.PP
\fB参数\fP
.RS 4
\fIwindow\fP 指定窗口 
.RE
.PP
\fB注解\fP
.RS 4
若不设置 window 参数，将默认以全局显示器屏幕为主 
.RE
.PP

.SS "\fBCursor\fP & S3GF::Cursor::operator= (const \fBCursor\fP & )\fR [delete]\fP"

.SS "\fBCursor\fP & S3GF::Cursor::operator= (\fBCursor\fP && )\fR [delete]\fP"

.SS "\fBVector2\fP S3GF::Cursor::position () const\fR [inline]\fP"

.PP
获取鼠标光标在获得焦点的窗口下的位置 
.PP
\fB返回\fP
.RS 4
返回鼠标光标相对获得焦点窗口下的位置 
.RE
.PP
\fB参见\fP
.RS 4
\fBglobalPosition\fP 

.PP
\fBmove\fP 
.RE
.PP

.SS "void S3GF::Cursor::setCursor (const std::string & path, int hot_x, int hot_y)\fR [inline]\fP"

.PP
设置自定义鼠标光标 
.PP
\fB参数\fP
.RS 4
\fIpath\fP 指定路径下加载鼠标光标 
.br
\fIhot_x\fP 中心点横坐标 
.br
\fIhot_y\fP 中心点纵坐标 
.RE
.PP
\fB注解\fP
.RS 4
若指定的 \fRpath\fP 参数无效，则无法设置！
.RE
.PP
从指定路径加载图像作为自定义鼠标光标，并设置热点坐标。 
.SS "void S3GF::Cursor::setCursor (const \fBStdCursor\fP & cursor)\fR [inline]\fP"

.PP
设置鼠标光标 
.PP
\fB参数\fP
.RS 4
\fIcursor\fP 指定光标类型 
.PP
.nf
Cursor::global()\->setCursor(Cursor::Hand);

.fi
.PP
 
.RE
.PP
\fB注解\fP
.RS 4
对于已经开启自定义鼠标光标的情况，将会改变对应类型的自定义光标； 若指定对应的光标类型没有定义鼠标光标，则会使用系统对应的鼠标光标！ 
.RE
.PP
\fB参见\fP
.RS 4
\fBcursor\fP 

.PP
\fBuserCustomEnabled\fP 

.PP
\fBStdCursor\fP 
.RE
.PP

.SS "void S3GF::Cursor::setCustomCursor (const \fBStdCursor\fP & stdCursor, const std::string & path, const \fBUserCustom::HotPoint\fP & hot_point)\fR [inline]\fP"

.PP
设置自定义鼠标光标 
.PP
\fB参数\fP
.RS 4
\fIstdCursor\fP 指定标准鼠标类型 
.br
\fIpath\fP 指定本地路径 
.br
\fIhot_point\fP 指定热点 
.RE
.PP
\fB参见\fP
.RS 4
\fBsetUserCustomEnabled\fP 

.PP
\fBuserCustomEnabled\fP 
.RE
.PP

.SS "void S3GF::Cursor::setUserCustomEnabled (bool enabled)\fR [inline]\fP"

.PP
是否允许使用自定义鼠标光标 
.PP
\fB参数\fP
.RS 4
\fIenabled\fP 启用/禁用 
.RE
.PP

.SS "void S3GF::Cursor::setVisible (bool visible)\fR [inline]\fP"

.PP
显示/隐藏鼠标光标 
.PP
\fB参数\fP
.RS 4
\fIvisible\fP 决定是否显示鼠标光标 
.RE
.PP
\fB参见\fP
.RS 4
\fBvisible\fP 
.RE
.PP

.SS "void S3GF::Cursor::unload ()\fR [inline]\fP"

.SS "bool S3GF::Cursor::userCustomEnabled () const\fR [inline]\fP"

.PP
当前是否使用自定义鼠标光标 
.SS "bool S3GF::Cursor::visible () const\fR [inline]\fP"

.PP
获取当前鼠标光标是否显示 
.PP
\fB参见\fP
.RS 4
\fBsetVisible\fP 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
