.TH "S3GF::TextureButton::TextureStatus" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TextureButton::TextureStatus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Button\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBTexture\fP * \fBnormal\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBactive\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBpressed\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBinvalid\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBchecked\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::active"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::checked"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::invalid"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::normal"

.SS "\fBTexture\fP* S3GF::TextureButton::TextureStatus::pressed"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
