.TH "S3GF::Size" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Size \- 尺寸、大小  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBSize\fP ()"
.br
.ti -1c
.RI "\fBSize\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "void \fBreset\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.RI "重新设置新的尺寸 "
.ti -1c
.RI "void \fBreset\fP (const \fBSize\fP &size)"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator+\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator\-\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator*\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator*\fP (float v) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator/\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "\fBSize\fP \fBoperator/\fP (float v) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator*=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator*=\fP (float v)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (const \fBSize\fP &s)"
.br
.ti -1c
.RI "void \fBoperator/=\fP (float v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSize\fP &s) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBSize\fP &s) const"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.in -1c
.SH "详细描述"
.PP 
尺寸、大小 

用于调整对象的尺寸、大小 
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Size::Size ()\fR [inline]\fP, \fR [explicit]\fP"

.SS "S3GF::Size::Size (float width, float height)\fR [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "bool S3GF::Size::operator!= (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "\fBSize\fP S3GF::Size::operator* (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "\fBSize\fP S3GF::Size::operator* (float v) const\fR [inline]\fP"

.SS "void S3GF::Size::operator*= (const \fBSize\fP & s)\fR [inline]\fP"

.SS "void S3GF::Size::operator*= (float v)\fR [inline]\fP"

.SS "\fBSize\fP S3GF::Size::operator+ (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "void S3GF::Size::operator+= (const \fBSize\fP & s)\fR [inline]\fP"

.SS "\fBSize\fP S3GF::Size::operator\- (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "void S3GF::Size::operator\-= (const \fBSize\fP & s)\fR [inline]\fP"

.SS "\fBSize\fP S3GF::Size::operator/ (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "\fBSize\fP S3GF::Size::operator/ (float v) const\fR [inline]\fP"

.SS "void S3GF::Size::operator/= (const \fBSize\fP & s)\fR [inline]\fP"

.SS "void S3GF::Size::operator/= (float v)\fR [inline]\fP"

.SS "bool S3GF::Size::operator< (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "bool S3GF::Size::operator<= (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "bool S3GF::Size::operator== (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "bool S3GF::Size::operator> (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "bool S3GF::Size::operator>= (const \fBSize\fP & s) const\fR [inline]\fP"

.SS "void S3GF::Size::reset (const \fBSize\fP & size)\fR [inline]\fP"

.SS "void S3GF::Size::reset (float width, float height)\fR [inline]\fP"

.PP
重新设置新的尺寸 
.PP
\fB参数\fP
.RS 4
\fIwidth\fP 
.br
\fIheight\fP 
.RE
.PP

.SH "类成员变量说明"
.PP 
.SS "float S3GF::Size::height"

.SS "float S3GF::Size::width"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
