.TH "S3GF::Engine" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Engine
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public 类型"

.in +1c
.ti -1c
.RI "using \fBconstIter\fP = std::unordered_map<SDL_WindowID, std::unique_ptr<\fBWindow\fP>>::const_iterator"
.br
.ti -1c
.RI "using \fBiter\fP = std::unordered_map<SDL_WindowID, std::unique_ptr<\fBWindow\fP>>::iterator"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBEngine\fP ()"
.br
.ti -1c
.RI "\fB~Engine\fP ()"
.br
.ti -1c
.RI "bool \fBisRunning\fP () const"
.br
.ti -1c
.RI "int \fBexec\fP ()"
.br
.ti -1c
.RI "void \fBnewWindow\fP (\fBWindow\fP *\fBwindow\fP)"
.br
.ti -1c
.RI "void \fBremoveWindow\fP (SDL_WindowID id)"
.br
.ti -1c
.RI "\fBWindow\fP * \fBwindow\fP (SDL_WindowID id=_main_window_id) const"
.br
.ti -1c
.RI "std::vector< uint32_t > \fBwindowIDList\fP () const"
.br
.ti -1c
.RI "\fBconstIter\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBiter\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBconstIter\fP \fBend\fP () const"
.br
.ti -1c
.RI "\fBiter\fP \fBend\fP ()"
.br
.ti -1c
.RI "size_t \fBwindowCount\fP ()"
.br
.ti -1c
.RI "void \fBsetFPS\fP (uint32_t \fBfps\fP)"
.br
.ti -1c
.RI "uint32_t \fBfps\fP () const"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static void \fBexit\fP (int code=0)"
.br
.ti -1c
.RI "static void \fBthrowFatalError\fP ()"
.br
.in -1c
.SH "成员类型定义说明"
.PP 
.SS "using \fBS3GF::Engine::constIter\fP = std::unordered_map<SDL_WindowID, std::unique_ptr<\fBWindow\fP>>::const_iterator"

.SS "using \fBS3GF::Engine::iter\fP = std::unordered_map<SDL_WindowID, std::unique_ptr<\fBWindow\fP>>::iterator"

.SH "构造及析构函数说明"
.PP 
.SS "S3GF::Engine::Engine ()\fR [explicit]\fP"

.SS "S3GF::Engine::~Engine ()"

.SH "成员函数说明"
.PP 
.SS "\fBiter\fP S3GF::Engine::begin ()\fR [inline]\fP"

.SS "\fBconstIter\fP S3GF::Engine::begin () const\fR [inline]\fP"

.SS "\fBiter\fP S3GF::Engine::end ()\fR [inline]\fP"

.SS "\fBconstIter\fP S3GF::Engine::end () const\fR [inline]\fP"

.SS "int S3GF::Engine::exec ()"

.SS "void S3GF::Engine::exit (int code = \fR0\fP)\fR [static]\fP"

.SS "uint32_t S3GF::Engine::fps () const"

.SS "bool S3GF::Engine::isRunning () const"

.SS "void S3GF::Engine::newWindow (\fBWindow\fP * window)"

.SS "void S3GF::Engine::removeWindow (SDL_WindowID id)"

.SS "void S3GF::Engine::setFPS (uint32_t fps)"

.SS "void S3GF::Engine::throwFatalError ()\fR [static]\fP"

.SS "\fBWindow\fP * S3GF::Engine::window (SDL_WindowID id = \fR_main_window_id\fP) const"

.SS "size_t S3GF::Engine::windowCount ()\fR [inline]\fP"

.SS "std::vector< uint32_t > S3GF::Engine::windowIDList () const"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
