.TH "S3GF::Button::ButtonSkin" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Button::ButtonSkin
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Button\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBColorStatus\fP \fBborder\fP"
.br
.ti -1c
.RI "\fBColorStatus\fP \fBbackground\fP"
.br
.ti -1c
.RI "\fBColorStatus\fP \fBfont\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "\fBColorStatus\fP S3GF::Button::ButtonSkin::background"

.SS "\fBColorStatus\fP S3GF::Button::ButtonSkin::border"

.SS "\fBColorStatus\fP S3GF::Button::ButtonSkin::font"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
