.TH "S3GF::DateTime" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::DateTime
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DateTime\&.h>\fP
.SS "类"

.in +1c
.ti -1c
.RI "struct \fBDT\fP"
.br
.in -1c
.SS "Public 类型"

.in +1c
.ti -1c
.RI "enum \fBWeekday\fP { \fBMonday\fP, \fBMon\fP = 0, \fBTuesday\fP, \fBTue\fP = 1, \fBWednesday\fP, \fBWed\fP = 2, \fBThursday\fP, \fBThu\fP = 3, \fBFriday\fP, \fBFri\fP = 4, \fBSaturday\fP, \fBSat\fP = 5, \fBSunday\fP, \fBSun\fP = 6 }"
.br
.ti -1c
.RI "enum \fBMonth\fP { \fBJanuary\fP, \fBJan\fP = 0, \fBFebruary\fP, \fBFeb\fP = 1, \fBMarch\fP, \fBMar\fP = 2, \fBApril\fP, \fBApr\fP = 3, \fBMay\fP, \fBJune\fP, \fBJun\fP = 5, \fBJuly\fP, \fBJul\fP = 6, \fBAugust\fP, \fBAug\fP = 7, \fBSeptember\fP, \fBSep\fP = 8, \fBOctober\fP, \fBOct\fP = 9, \fBNovember\fP, \fBNov\fP = 10, \fBDecember\fP, \fBDec\fP = 11 }"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBDateTime\fP ()=delete"
.br
.ti -1c
.RI "\fB~DateTime\fP ()=delete"
.br
.ti -1c
.RI "\fBDateTime\fP (const \fBDateTime\fP &)=delete"
.br
.ti -1c
.RI "\fBDateTime\fP (\fBDateTime\fP &&)=delete"
.br
.ti -1c
.RI "\fBDateTime\fP & \fBoperator=\fP (const \fBDateTime\fP &)=delete"
.br
.ti -1c
.RI "\fBDateTime\fP & \fBoperator=\fP (\fBDateTime\fP &&)=delete"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static const char * \fBweekdayStr\fP (\fBWeekday\fP weekday, bool short_name=false)"
.br
.ti -1c
.RI "static const char * \fBweekdayChineseStr\fP (\fBWeekday\fP weekday)"
.br
.ti -1c
.RI "static const char * \fBmonthStr\fP (\fBMonth\fP month, bool short_name=false)"
.br
.ti -1c
.RI "static bool \fBsetDefaultTimezone\fP (const std::string &tz)"
.br
.ti -1c
.RI "static std::string_view \fBcurrentTimezone\fP ()"
.br
.ti -1c
.RI "static uint64_t \fBcurrentTimestamp\fP ()"
.br
.ti -1c
.RI "static std::string \fBnow\fP ()"
.br
.ti -1c
.RI "static \fBDT\fP \fBcurrentDateTime\fP ()"
.br
.ti -1c
.RI "static uint64_t \fBgenerateTimestamp\fP (const \fBDT\fP &datetime)"
.br
.ti -1c
.RI "static \fBDT\fP \fBparseFromTimestamp\fP (uint64_t timestamp)"
.br
.ti -1c
.RI "static std::string \fBformatDateTime\fP (const \fBDT\fP &datetime, const std::string &format)"
.br
.ti -1c
.RI "static std::string \fBformatCurrentDateTime\fP (const std::string &format)"
.br
.in -1c
.SH "成员枚举类型说明"
.PP 
.SS "enum \fBS3GF::DateTime::Month\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\f(BIJanuary \fP
.TP
\f(BIJan \fP
.TP
\f(BIFebruary \fP
.TP
\f(BIFeb \fP
.TP
\f(BIMarch \fP
.TP
\f(BIMar \fP
.TP
\f(BIApril \fP
.TP
\f(BIApr \fP
.TP
\f(BIMay \fP
.TP
\f(BIJune \fP
.TP
\f(BIJun \fP
.TP
\f(BIJuly \fP
.TP
\f(BIJul \fP
.TP
\f(BIAugust \fP
.TP
\f(BIAug \fP
.TP
\f(BISeptember \fP
.TP
\f(BISep \fP
.TP
\f(BIOctober \fP
.TP
\f(BIOct \fP
.TP
\f(BINovember \fP
.TP
\f(BINov \fP
.TP
\f(BIDecember \fP
.TP
\f(BIDec \fP
.SS "enum \fBS3GF::DateTime::Weekday\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\f(BIMonday \fP
.TP
\f(BIMon \fP
.TP
\f(BITuesday \fP
.TP
\f(BITue \fP
.TP
\f(BIWednesday \fP
.TP
\f(BIWed \fP
.TP
\f(BIThursday \fP
.TP
\f(BIThu \fP
.TP
\f(BIFriday \fP
.TP
\f(BIFri \fP
.TP
\f(BISaturday \fP
.TP
\f(BISat \fP
.TP
\f(BISunday \fP
.TP
\f(BISun \fP
.SH "构造及析构函数说明"
.PP 
.SS "S3GF::DateTime::DateTime ()\fR [delete]\fP"

.SS "S3GF::DateTime::~DateTime ()\fR [delete]\fP"

.SS "S3GF::DateTime::DateTime (const \fBDateTime\fP & )\fR [delete]\fP"

.SS "S3GF::DateTime::DateTime (\fBDateTime\fP && )\fR [delete]\fP"

.SH "成员函数说明"
.PP 
.SS "\fBDT\fP S3GF::DateTime::currentDateTime ()\fR [inline]\fP, \fR [static]\fP"

.SS "uint64_t S3GF::DateTime::currentTimestamp ()\fR [inline]\fP, \fR [static]\fP"

.SS "std::string_view S3GF::DateTime::currentTimezone ()\fR [inline]\fP, \fR [static]\fP"

.SS "std::string S3GF::DateTime::formatCurrentDateTime (const std::string & format)\fR [inline]\fP, \fR [static]\fP"

.SS "std::string S3GF::DateTime::formatDateTime (const \fBDT\fP & datetime, const std::string & format)\fR [inline]\fP, \fR [static]\fP"

.SS "uint64_t S3GF::DateTime::generateTimestamp (const \fBDT\fP & datetime)\fR [inline]\fP, \fR [static]\fP"

.SS "const char * S3GF::DateTime::monthStr (\fBMonth\fP month, bool short_name = \fRfalse\fP)\fR [inline]\fP, \fR [static]\fP"

.SS "std::string S3GF::DateTime::now ()\fR [inline]\fP, \fR [static]\fP"

.SS "\fBDateTime\fP & S3GF::DateTime::operator= (const \fBDateTime\fP & )\fR [delete]\fP"

.SS "\fBDateTime\fP & S3GF::DateTime::operator= (\fBDateTime\fP && )\fR [delete]\fP"

.SS "\fBDT\fP S3GF::DateTime::parseFromTimestamp (uint64_t timestamp)\fR [inline]\fP, \fR [static]\fP"

.SS "bool S3GF::DateTime::setDefaultTimezone (const std::string & tz)\fR [inline]\fP, \fR [static]\fP"

.SS "const char * S3GF::DateTime::weekdayChineseStr (\fBWeekday\fP weekday)\fR [inline]\fP, \fR [static]\fP"

.SS "const char * S3GF::DateTime::weekdayStr (\fBWeekday\fP weekday, bool short_name = \fRfalse\fP)\fR [inline]\fP, \fR [static]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
