.TH "S3GF::TextSystem::FontEngine" 3 "2025年 十一月 27日 星期四 19:54:22" "Version v0.1.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::TextSystem::FontEngine
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Core\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "TTF_TextEngine * \fBengine\fP"
.br
.ti -1c
.RI "TTF_TextEngine * \fBsurface_engine\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBFont\fP > \fBfont\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "TTF_TextEngine* S3GF::TextSystem::FontEngine::engine"

.SS "std::shared_ptr<\fBFont\fP> S3GF::TextSystem::FontEngine::font"

.SS "TTF_TextEngine* S3GF::TextSystem::FontEngine::surface_engine"


.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
