.TH "D:/Coding/S3GF/src/MultiThread/ThreadPool.h" 3 "2025年 十一月 20日 星期四 19:39:35" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/MultiThread/ThreadPool.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Libs\&.h'\fP
.br
\fR#include 'Utils/Logger\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBS3GF::ThreadPool\fP"
.br
.ti -1c
.RI "class \fBS3GF::TasksManager\fP"
.br
.ti -1c
.RI "struct \fBS3GF::TasksManager::Task\fP"
.br
.ti -1c
.RI "struct \fBS3GF::TasksManager::TaskCmp\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP 空间 "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBsleep\fP(sec)"
.br
.ti -1c
.RI "#define \fBsleepMS\fP(millisec)"
.br
.ti -1c
.RI "#define \fBsleepNS\fP(nanosec)"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define sleep( sec)"
\fB值:\fP
.nf
std::this_thread::sleep_for(std::chrono::seconds(sec))
.PP
.fi

.SS "#define sleepMS( millisec)"
\fB值:\fP
.nf
std::this_thread::sleep_for(std::chrono::milliseconds(millisec))
.PP
.fi

.SS "#define sleepNS( nanosec)"
\fB值:\fP
.nf
std::this_thread::sleep_for(std::chrono::nanoseconds(nanosec))
.PP
.fi

.SH "作者"
.PP 
由 Doyxgen 通过分析 S3GF 的 源代码自动生成\&.
